import type * as grpc from '@grpc/grpc-js';
import type { EnumTypeDefinition, MessageTypeDefinition } from '@grpc/proto-loader';

import type { ZetaSqlLocalServiceClient as _zetasql_local_service_ZetaSqlLocalServiceClient, ZetaSqlLocalServiceDefinition as _zetasql_local_service_ZetaSqlLocalServiceDefinition } from './zetasql/local_service/ZetaSqlLocalService';

type SubtypeConstructor<Constructor extends new (...args: any) => any, Subtype> = {
  new(...args: ConstructorParameters<Constructor>): Subtype;
};

export interface ProtoGrpcType {
  google: {
    protobuf: {
      DescriptorProto: MessageTypeDefinition
      Empty: MessageTypeDefinition
      EnumDescriptorProto: MessageTypeDefinition
      EnumOptions: MessageTypeDefinition
      EnumValueDescriptorProto: MessageTypeDefinition
      EnumValueOptions: MessageTypeDefinition
      FieldDescriptorProto: MessageTypeDefinition
      FieldOptions: MessageTypeDefinition
      FileDescriptorProto: MessageTypeDefinition
      FileDescriptorSet: MessageTypeDefinition
      FileOptions: MessageTypeDefinition
      GeneratedCodeInfo: MessageTypeDefinition
      MessageOptions: MessageTypeDefinition
      MethodDescriptorProto: MessageTypeDefinition
      MethodOptions: MessageTypeDefinition
      OneofDescriptorProto: MessageTypeDefinition
      OneofOptions: MessageTypeDefinition
      ServiceDescriptorProto: MessageTypeDefinition
      ServiceOptions: MessageTypeDefinition
      SourceCodeInfo: MessageTypeDefinition
      Timestamp: MessageTypeDefinition
      UninterpretedOption: MessageTypeDefinition
    }
  }
  zetasql: {
    ASTAbortBatchStatementProto: MessageTypeDefinition
    ASTAddColumnActionProto: MessageTypeDefinition
    ASTAddConstraintActionProto: MessageTypeDefinition
    ASTAddSubEntityActionProto: MessageTypeDefinition
    ASTAddToRestricteeListClauseProto: MessageTypeDefinition
    ASTAddTtlActionProto: MessageTypeDefinition
    ASTAliasProto: MessageTypeDefinition
    ASTAliasedQueryListProto: MessageTypeDefinition
    ASTAliasedQueryProto: MessageTypeDefinition
    ASTAlterActionListProto: MessageTypeDefinition
    ASTAlterActionProto: MessageTypeDefinition
    ASTAlterAllRowAccessPoliciesStatementProto: MessageTypeDefinition
    ASTAlterApproxViewStatementProto: MessageTypeDefinition
    ASTAlterColumnDropDefaultActionProto: MessageTypeDefinition
    ASTAlterColumnDropNotNullActionProto: MessageTypeDefinition
    ASTAlterColumnOptionsActionProto: MessageTypeDefinition
    ASTAlterColumnSetDefaultActionProto: MessageTypeDefinition
    ASTAlterColumnTypeActionProto: MessageTypeDefinition
    ASTAlterConstraintEnforcementActionProto: MessageTypeDefinition
    ASTAlterConstraintSetOptionsActionProto: MessageTypeDefinition
    ASTAlterDatabaseStatementProto: MessageTypeDefinition
    ASTAlterEntityStatementProto: MessageTypeDefinition
    ASTAlterMaterializedViewStatementProto: MessageTypeDefinition
    ASTAlterModelStatementProto: MessageTypeDefinition
    ASTAlterPrivilegeRestrictionStatementProto: MessageTypeDefinition
    ASTAlterRowAccessPolicyStatementProto: MessageTypeDefinition
    ASTAlterSchemaStatementProto: MessageTypeDefinition
    ASTAlterStatementBaseProto: MessageTypeDefinition
    ASTAlterSubEntityActionProto: MessageTypeDefinition
    ASTAlterTableStatementProto: MessageTypeDefinition
    ASTAlterViewStatementProto: MessageTypeDefinition
    ASTAnalyticFunctionCallProto: MessageTypeDefinition
    ASTAnalyzeStatementProto: MessageTypeDefinition
    ASTAndExprProto: MessageTypeDefinition
    ASTAnySomeAllOpEnums: MessageTypeDefinition
    ASTAnySomeAllOpProto: MessageTypeDefinition
    ASTArrayColumnSchemaProto: MessageTypeDefinition
    ASTArrayConstructorProto: MessageTypeDefinition
    ASTArrayElementProto: MessageTypeDefinition
    ASTArrayTypeProto: MessageTypeDefinition
    ASTAssertRowsModifiedProto: MessageTypeDefinition
    ASTAssertStatementProto: MessageTypeDefinition
    ASTAssignmentFromStructProto: MessageTypeDefinition
    ASTAuxLoadDataFromFilesOptionsListProto: MessageTypeDefinition
    ASTAuxLoadDataPartitionsClauseProto: MessageTypeDefinition
    ASTAuxLoadDataStatementEnums: MessageTypeDefinition
    ASTAuxLoadDataStatementProto: MessageTypeDefinition
    ASTBeginEndBlockProto: MessageTypeDefinition
    ASTBeginStatementProto: MessageTypeDefinition
    ASTBetweenExpressionProto: MessageTypeDefinition
    ASTBigNumericLiteralProto: MessageTypeDefinition
    ASTBinaryExpressionEnums: MessageTypeDefinition
    ASTBinaryExpressionProto: MessageTypeDefinition
    ASTBitwiseShiftExpressionProto: MessageTypeDefinition
    ASTBooleanLiteralProto: MessageTypeDefinition
    ASTBracedConstructorFieldProto: MessageTypeDefinition
    ASTBracedConstructorFieldValueProto: MessageTypeDefinition
    ASTBracedConstructorProto: MessageTypeDefinition
    ASTBracedNewConstructorProto: MessageTypeDefinition
    ASTBreakContinueStatementEnums: MessageTypeDefinition
    ASTBreakContinueStatementProto: MessageTypeDefinition
    ASTBreakStatementProto: MessageTypeDefinition
    ASTBytesLiteralProto: MessageTypeDefinition
    ASTCallStatementProto: MessageTypeDefinition
    ASTCaseNoValueExpressionProto: MessageTypeDefinition
    ASTCaseStatementProto: MessageTypeDefinition
    ASTCaseValueExpressionProto: MessageTypeDefinition
    ASTCastExpressionProto: MessageTypeDefinition
    ASTCheckConstraintProto: MessageTypeDefinition
    ASTClampedBetweenModifierProto: MessageTypeDefinition
    ASTCloneDataSourceListProto: MessageTypeDefinition
    ASTCloneDataSourceProto: MessageTypeDefinition
    ASTCloneDataStatementProto: MessageTypeDefinition
    ASTClusterByProto: MessageTypeDefinition
    ASTCollateProto: MessageTypeDefinition
    ASTColumnAttributeListProto: MessageTypeDefinition
    ASTColumnAttributeProto: MessageTypeDefinition
    ASTColumnDefinitionProto: MessageTypeDefinition
    ASTColumnListProto: MessageTypeDefinition
    ASTColumnPositionEnums: MessageTypeDefinition
    ASTColumnPositionProto: MessageTypeDefinition
    ASTColumnSchemaProto: MessageTypeDefinition
    ASTColumnWithOptionsListProto: MessageTypeDefinition
    ASTColumnWithOptionsProto: MessageTypeDefinition
    ASTCommitStatementProto: MessageTypeDefinition
    ASTConnectionClauseProto: MessageTypeDefinition
    ASTContinueStatementProto: MessageTypeDefinition
    ASTCopyDataSourceProto: MessageTypeDefinition
    ASTCreateApproxViewStatementProto: MessageTypeDefinition
    ASTCreateConstantStatementProto: MessageTypeDefinition
    ASTCreateDatabaseStatementProto: MessageTypeDefinition
    ASTCreateEntityStatementProto: MessageTypeDefinition
    ASTCreateExternalTableStatementProto: MessageTypeDefinition
    ASTCreateFunctionStatementProto: MessageTypeDefinition
    ASTCreateFunctionStmtBaseEnums: MessageTypeDefinition
    ASTCreateFunctionStmtBaseProto: MessageTypeDefinition
    ASTCreateIndexStatementProto: MessageTypeDefinition
    ASTCreateMaterializedViewStatementProto: MessageTypeDefinition
    ASTCreateModelStatementProto: MessageTypeDefinition
    ASTCreatePrivilegeRestrictionStatementProto: MessageTypeDefinition
    ASTCreateProcedureStatementProto: MessageTypeDefinition
    ASTCreateRowAccessPolicyStatementProto: MessageTypeDefinition
    ASTCreateSchemaStatementProto: MessageTypeDefinition
    ASTCreateSnapshotTableStatementProto: MessageTypeDefinition
    ASTCreateStatementEnums: MessageTypeDefinition
    ASTCreateStatementProto: MessageTypeDefinition
    ASTCreateTableFunctionStatementProto: MessageTypeDefinition
    ASTCreateTableStatementProto: MessageTypeDefinition
    ASTCreateTableStmtBaseProto: MessageTypeDefinition
    ASTCreateViewStatementBaseProto: MessageTypeDefinition
    ASTCreateViewStatementProto: MessageTypeDefinition
    ASTCubeProto: MessageTypeDefinition
    ASTDateOrTimeLiteralProto: MessageTypeDefinition
    ASTDdlStatementProto: MessageTypeDefinition
    ASTDefaultLiteralProto: MessageTypeDefinition
    ASTDefineMacroStatementProto: MessageTypeDefinition
    ASTDefineTableStatementProto: MessageTypeDefinition
    ASTDeleteStatementProto: MessageTypeDefinition
    ASTDescribeStatementProto: MessageTypeDefinition
    ASTDescriptorColumnListProto: MessageTypeDefinition
    ASTDescriptorColumnProto: MessageTypeDefinition
    ASTDescriptorProto: MessageTypeDefinition
    ASTDotGeneralizedFieldProto: MessageTypeDefinition
    ASTDotIdentifierProto: MessageTypeDefinition
    ASTDotStarProto: MessageTypeDefinition
    ASTDotStarWithModifiersProto: MessageTypeDefinition
    ASTDropAllRowAccessPoliciesStatementProto: MessageTypeDefinition
    ASTDropColumnActionProto: MessageTypeDefinition
    ASTDropConstraintActionProto: MessageTypeDefinition
    ASTDropEntityStatementProto: MessageTypeDefinition
    ASTDropFunctionStatementProto: MessageTypeDefinition
    ASTDropMaterializedViewStatementProto: MessageTypeDefinition
    ASTDropPrimaryKeyActionProto: MessageTypeDefinition
    ASTDropPrivilegeRestrictionStatementProto: MessageTypeDefinition
    ASTDropRowAccessPolicyStatementProto: MessageTypeDefinition
    ASTDropSearchIndexStatementProto: MessageTypeDefinition
    ASTDropSnapshotTableStatementProto: MessageTypeDefinition
    ASTDropStatementEnums: MessageTypeDefinition
    ASTDropStatementProto: MessageTypeDefinition
    ASTDropSubEntityActionProto: MessageTypeDefinition
    ASTDropTableFunctionStatementProto: MessageTypeDefinition
    ASTDropTtlActionProto: MessageTypeDefinition
    ASTElementTypeColumnSchemaProto: MessageTypeDefinition
    ASTElseifClauseListProto: MessageTypeDefinition
    ASTElseifClauseProto: MessageTypeDefinition
    ASTExceptionHandlerListProto: MessageTypeDefinition
    ASTExceptionHandlerProto: MessageTypeDefinition
    ASTExecuteImmediateStatementProto: MessageTypeDefinition
    ASTExecuteIntoClauseProto: MessageTypeDefinition
    ASTExecuteUsingArgumentProto: MessageTypeDefinition
    ASTExecuteUsingClauseProto: MessageTypeDefinition
    ASTExplainStatementProto: MessageTypeDefinition
    ASTExportDataStatementProto: MessageTypeDefinition
    ASTExportMetadataStatementProto: MessageTypeDefinition
    ASTExportModelStatementProto: MessageTypeDefinition
    ASTExpressionProto: MessageTypeDefinition
    ASTExpressionSubqueryEnums: MessageTypeDefinition
    ASTExpressionSubqueryProto: MessageTypeDefinition
    ASTExpressionWithAliasProto: MessageTypeDefinition
    ASTExpressionWithOptAliasProto: MessageTypeDefinition
    ASTExtractExpressionProto: MessageTypeDefinition
    ASTFilterFieldsArgEnums: MessageTypeDefinition
    ASTFilterFieldsArgProto: MessageTypeDefinition
    ASTFilterUsingClauseProto: MessageTypeDefinition
    ASTFloatLiteralProto: MessageTypeDefinition
    ASTForInStatementProto: MessageTypeDefinition
    ASTForSystemTimeProto: MessageTypeDefinition
    ASTForeignKeyActionsEnums: MessageTypeDefinition
    ASTForeignKeyActionsProto: MessageTypeDefinition
    ASTForeignKeyColumnAttributeProto: MessageTypeDefinition
    ASTForeignKeyProto: MessageTypeDefinition
    ASTForeignKeyReferenceEnums: MessageTypeDefinition
    ASTForeignKeyReferenceProto: MessageTypeDefinition
    ASTFormatClauseProto: MessageTypeDefinition
    ASTFromClauseProto: MessageTypeDefinition
    ASTFunctionCallEnums: MessageTypeDefinition
    ASTFunctionCallProto: MessageTypeDefinition
    ASTFunctionCallWithGroupRowsProto: MessageTypeDefinition
    ASTFunctionDeclarationProto: MessageTypeDefinition
    ASTFunctionParameterEnums: MessageTypeDefinition
    ASTFunctionParameterProto: MessageTypeDefinition
    ASTFunctionParametersProto: MessageTypeDefinition
    ASTFunctionTypeArgListProto: MessageTypeDefinition
    ASTFunctionTypeProto: MessageTypeDefinition
    ASTGeneralizedPathExpressionProto: MessageTypeDefinition
    ASTGeneratedColumnInfoEnums: MessageTypeDefinition
    ASTGeneratedColumnInfoProto: MessageTypeDefinition
    ASTGrantStatementProto: MessageTypeDefinition
    ASTGrantToClauseProto: MessageTypeDefinition
    ASTGranteeListProto: MessageTypeDefinition
    ASTGroupByAllProto: MessageTypeDefinition
    ASTGroupByProto: MessageTypeDefinition
    ASTGroupingItemProto: MessageTypeDefinition
    ASTGroupingSetListProto: MessageTypeDefinition
    ASTGroupingSetProto: MessageTypeDefinition
    ASTHavingModifierEnums: MessageTypeDefinition
    ASTHavingModifierProto: MessageTypeDefinition
    ASTHavingProto: MessageTypeDefinition
    ASTHiddenColumnAttributeProto: MessageTypeDefinition
    ASTHintEntryProto: MessageTypeDefinition
    ASTHintProto: MessageTypeDefinition
    ASTHintedStatementProto: MessageTypeDefinition
    ASTIdentifierListProto: MessageTypeDefinition
    ASTIdentifierProto: MessageTypeDefinition
    ASTIfStatementProto: MessageTypeDefinition
    ASTImportStatementEnums: MessageTypeDefinition
    ASTImportStatementProto: MessageTypeDefinition
    ASTInExpressionProto: MessageTypeDefinition
    ASTInListProto: MessageTypeDefinition
    ASTIndexAllColumnsProto: MessageTypeDefinition
    ASTIndexItemListProto: MessageTypeDefinition
    ASTIndexStoringExpressionListProto: MessageTypeDefinition
    ASTIndexUnnestExpressionListProto: MessageTypeDefinition
    ASTInferredTypeColumnSchemaProto: MessageTypeDefinition
    ASTInputOutputClauseProto: MessageTypeDefinition
    ASTInsertStatementEnums: MessageTypeDefinition
    ASTInsertStatementProto: MessageTypeDefinition
    ASTInsertValuesRowListProto: MessageTypeDefinition
    ASTInsertValuesRowProto: MessageTypeDefinition
    ASTIntLiteralProto: MessageTypeDefinition
    ASTIntervalExprProto: MessageTypeDefinition
    ASTIntoAliasProto: MessageTypeDefinition
    ASTJSONLiteralProto: MessageTypeDefinition
    ASTJoinEnums: MessageTypeDefinition
    ASTJoinProto: MessageTypeDefinition
    ASTLabelProto: MessageTypeDefinition
    ASTLambdaProto: MessageTypeDefinition
    ASTLeafProto: MessageTypeDefinition
    ASTLikeExpressionProto: MessageTypeDefinition
    ASTLimitOffsetProto: MessageTypeDefinition
    ASTLocationProto: MessageTypeDefinition
    ASTLoopStatementProto: MessageTypeDefinition
    ASTMacroBodyProto: MessageTypeDefinition
    ASTMaxLiteralProto: MessageTypeDefinition
    ASTMergeActionEnums: MessageTypeDefinition
    ASTMergeActionProto: MessageTypeDefinition
    ASTMergeStatementProto: MessageTypeDefinition
    ASTMergeWhenClauseEnums: MessageTypeDefinition
    ASTMergeWhenClauseListProto: MessageTypeDefinition
    ASTMergeWhenClauseProto: MessageTypeDefinition
    ASTModelClauseProto: MessageTypeDefinition
    ASTModuleStatementProto: MessageTypeDefinition
    ASTNamedArgumentProto: MessageTypeDefinition
    ASTNewConstructorArgProto: MessageTypeDefinition
    ASTNewConstructorProto: MessageTypeDefinition
    ASTNodeProto: MessageTypeDefinition
    ASTNotNullColumnAttributeProto: MessageTypeDefinition
    ASTNullLiteralProto: MessageTypeDefinition
    ASTNullOrderProto: MessageTypeDefinition
    ASTNumericLiteralProto: MessageTypeDefinition
    ASTOnClauseProto: MessageTypeDefinition
    ASTOnOrUsingClauseListProto: MessageTypeDefinition
    ASTOptionsEntryProto: MessageTypeDefinition
    ASTOptionsListProto: MessageTypeDefinition
    ASTOrExprProto: MessageTypeDefinition
    ASTOrderByProto: MessageTypeDefinition
    ASTOrderingExpressionEnums: MessageTypeDefinition
    ASTOrderingExpressionProto: MessageTypeDefinition
    ASTParameterAssignmentProto: MessageTypeDefinition
    ASTParameterExprBaseProto: MessageTypeDefinition
    ASTParameterExprProto: MessageTypeDefinition
    ASTParenthesizedJoinProto: MessageTypeDefinition
    ASTPartitionByProto: MessageTypeDefinition
    ASTPathExpressionListProto: MessageTypeDefinition
    ASTPathExpressionProto: MessageTypeDefinition
    ASTPivotClauseProto: MessageTypeDefinition
    ASTPivotExpressionListProto: MessageTypeDefinition
    ASTPivotExpressionProto: MessageTypeDefinition
    ASTPivotValueListProto: MessageTypeDefinition
    ASTPivotValueProto: MessageTypeDefinition
    ASTPrimaryKeyColumnAttributeProto: MessageTypeDefinition
    ASTPrimaryKeyElementListProto: MessageTypeDefinition
    ASTPrimaryKeyElementProto: MessageTypeDefinition
    ASTPrimaryKeyProto: MessageTypeDefinition
    ASTPrivilegeProto: MessageTypeDefinition
    ASTPrivilegesProto: MessageTypeDefinition
    ASTQualifyProto: MessageTypeDefinition
    ASTQueryExpressionProto: MessageTypeDefinition
    ASTQueryProto: MessageTypeDefinition
    ASTQueryStatementProto: MessageTypeDefinition
    ASTRaiseStatementProto: MessageTypeDefinition
    ASTRangeColumnSchemaProto: MessageTypeDefinition
    ASTRangeLiteralProto: MessageTypeDefinition
    ASTRangeTypeProto: MessageTypeDefinition
    ASTRemoveFromRestricteeListClauseProto: MessageTypeDefinition
    ASTRenameColumnActionProto: MessageTypeDefinition
    ASTRenameStatementProto: MessageTypeDefinition
    ASTRenameToClauseProto: MessageTypeDefinition
    ASTRepeatStatementProto: MessageTypeDefinition
    ASTRepeatableClauseProto: MessageTypeDefinition
    ASTReplaceFieldsArgProto: MessageTypeDefinition
    ASTReplaceFieldsExpressionProto: MessageTypeDefinition
    ASTReplaceTtlActionProto: MessageTypeDefinition
    ASTRestrictToClauseProto: MessageTypeDefinition
    ASTReturnStatementProto: MessageTypeDefinition
    ASTReturningClauseProto: MessageTypeDefinition
    ASTRevokeFromClauseProto: MessageTypeDefinition
    ASTRevokeStatementProto: MessageTypeDefinition
    ASTRollbackStatementProto: MessageTypeDefinition
    ASTRollupProto: MessageTypeDefinition
    ASTRunBatchStatementProto: MessageTypeDefinition
    ASTSampleClauseProto: MessageTypeDefinition
    ASTSampleSizeEnums: MessageTypeDefinition
    ASTSampleSizeProto: MessageTypeDefinition
    ASTSampleSuffixProto: MessageTypeDefinition
    ASTScriptProto: MessageTypeDefinition
    ASTScriptStatementProto: MessageTypeDefinition
    ASTSelectAsEnums: MessageTypeDefinition
    ASTSelectAsProto: MessageTypeDefinition
    ASTSelectColumnProto: MessageTypeDefinition
    ASTSelectListProto: MessageTypeDefinition
    ASTSelectProto: MessageTypeDefinition
    ASTSelectWithProto: MessageTypeDefinition
    ASTSequenceArgProto: MessageTypeDefinition
    ASTSetAsActionProto: MessageTypeDefinition
    ASTSetCollateClauseProto: MessageTypeDefinition
    ASTSetOperationAllOrDistinctProto: MessageTypeDefinition
    ASTSetOperationColumnMatchModeProto: MessageTypeDefinition
    ASTSetOperationColumnPropagationModeProto: MessageTypeDefinition
    ASTSetOperationEnums: MessageTypeDefinition
    ASTSetOperationMetadataListProto: MessageTypeDefinition
    ASTSetOperationMetadataProto: MessageTypeDefinition
    ASTSetOperationProto: MessageTypeDefinition
    ASTSetOperationTypeProto: MessageTypeDefinition
    ASTSetOptionsActionProto: MessageTypeDefinition
    ASTSetTransactionStatementProto: MessageTypeDefinition
    ASTShowStatementProto: MessageTypeDefinition
    ASTSimpleColumnSchemaProto: MessageTypeDefinition
    ASTSimpleTypeProto: MessageTypeDefinition
    ASTSingleAssignmentProto: MessageTypeDefinition
    ASTSpannerAlterColumnActionProto: MessageTypeDefinition
    ASTSpannerInterleaveClauseEnums: MessageTypeDefinition
    ASTSpannerInterleaveClauseProto: MessageTypeDefinition
    ASTSpannerSetOnDeleteActionProto: MessageTypeDefinition
    ASTSpannerTableOptionsProto: MessageTypeDefinition
    ASTSqlFunctionBodyProto: MessageTypeDefinition
    ASTStarExceptListProto: MessageTypeDefinition
    ASTStarModifiersProto: MessageTypeDefinition
    ASTStarProto: MessageTypeDefinition
    ASTStarReplaceItemProto: MessageTypeDefinition
    ASTStarWithModifiersProto: MessageTypeDefinition
    ASTStartBatchStatementProto: MessageTypeDefinition
    ASTStatementListProto: MessageTypeDefinition
    ASTStatementProto: MessageTypeDefinition
    ASTStringLiteralProto: MessageTypeDefinition
    ASTStructColumnFieldProto: MessageTypeDefinition
    ASTStructColumnSchemaProto: MessageTypeDefinition
    ASTStructConstructorArgProto: MessageTypeDefinition
    ASTStructConstructorWithKeywordProto: MessageTypeDefinition
    ASTStructConstructorWithParensProto: MessageTypeDefinition
    ASTStructFieldProto: MessageTypeDefinition
    ASTStructTypeProto: MessageTypeDefinition
    ASTSystemVariableAssignmentProto: MessageTypeDefinition
    ASTSystemVariableExprProto: MessageTypeDefinition
    ASTTVFArgumentProto: MessageTypeDefinition
    ASTTVFProto: MessageTypeDefinition
    ASTTVFSchemaColumnProto: MessageTypeDefinition
    ASTTVFSchemaProto: MessageTypeDefinition
    ASTTableAndColumnInfoListProto: MessageTypeDefinition
    ASTTableAndColumnInfoProto: MessageTypeDefinition
    ASTTableClauseProto: MessageTypeDefinition
    ASTTableConstraintProto: MessageTypeDefinition
    ASTTableDataSourceProto: MessageTypeDefinition
    ASTTableElementListProto: MessageTypeDefinition
    ASTTableElementProto: MessageTypeDefinition
    ASTTableExpressionProto: MessageTypeDefinition
    ASTTablePathExpressionProto: MessageTypeDefinition
    ASTTableSubqueryProto: MessageTypeDefinition
    ASTTemplatedParameterTypeEnums: MessageTypeDefinition
    ASTTemplatedParameterTypeProto: MessageTypeDefinition
    ASTTransactionIsolationLevelProto: MessageTypeDefinition
    ASTTransactionModeListProto: MessageTypeDefinition
    ASTTransactionModeProto: MessageTypeDefinition
    ASTTransactionReadWriteModeEnums: MessageTypeDefinition
    ASTTransactionReadWriteModeProto: MessageTypeDefinition
    ASTTransformClauseProto: MessageTypeDefinition
    ASTTruncateStatementProto: MessageTypeDefinition
    ASTTtlClauseProto: MessageTypeDefinition
    ASTTypeParameterListProto: MessageTypeDefinition
    ASTTypeProto: MessageTypeDefinition
    ASTUnaryExpressionEnums: MessageTypeDefinition
    ASTUnaryExpressionProto: MessageTypeDefinition
    ASTUndropStatementProto: MessageTypeDefinition
    ASTUnnestExpressionProto: MessageTypeDefinition
    ASTUnnestExpressionWithOptAliasAndOffsetProto: MessageTypeDefinition
    ASTUnpivotClauseEnums: MessageTypeDefinition
    ASTUnpivotClauseProto: MessageTypeDefinition
    ASTUnpivotInItemLabelProto: MessageTypeDefinition
    ASTUnpivotInItemListProto: MessageTypeDefinition
    ASTUnpivotInItemProto: MessageTypeDefinition
    ASTUntilClauseProto: MessageTypeDefinition
    ASTUpdateItemListProto: MessageTypeDefinition
    ASTUpdateItemProto: MessageTypeDefinition
    ASTUpdateSetValueProto: MessageTypeDefinition
    ASTUpdateStatementProto: MessageTypeDefinition
    ASTUsingClauseProto: MessageTypeDefinition
    ASTVariableDeclarationProto: MessageTypeDefinition
    ASTWhenThenClauseListProto: MessageTypeDefinition
    ASTWhenThenClauseProto: MessageTypeDefinition
    ASTWhereClauseProto: MessageTypeDefinition
    ASTWhileStatementProto: MessageTypeDefinition
    ASTWindowClauseProto: MessageTypeDefinition
    ASTWindowDefinitionProto: MessageTypeDefinition
    ASTWindowFrameEnums: MessageTypeDefinition
    ASTWindowFrameExprEnums: MessageTypeDefinition
    ASTWindowFrameExprProto: MessageTypeDefinition
    ASTWindowFrameProto: MessageTypeDefinition
    ASTWindowSpecificationProto: MessageTypeDefinition
    ASTWithClauseProto: MessageTypeDefinition
    ASTWithConnectionClauseProto: MessageTypeDefinition
    ASTWithExpressionProto: MessageTypeDefinition
    ASTWithGroupRowsProto: MessageTypeDefinition
    ASTWithOffsetProto: MessageTypeDefinition
    ASTWithPartitionColumnsClauseProto: MessageTypeDefinition
    ASTWithReportModifierProto: MessageTypeDefinition
    ASTWithWeightProto: MessageTypeDefinition
    AllowedHintsAndOptionsProto: MessageTypeDefinition
    AnalyzerOptionsProto: MessageTypeDefinition
    AnnotationMapProto: MessageTypeDefinition
    AnnotationProto: MessageTypeDefinition
    AnyASTAlterActionProto: MessageTypeDefinition
    AnyASTAlterStatementBaseProto: MessageTypeDefinition
    AnyASTBreakContinueStatementProto: MessageTypeDefinition
    AnyASTColumnAttributeProto: MessageTypeDefinition
    AnyASTColumnSchemaProto: MessageTypeDefinition
    AnyASTCreateFunctionStmtBaseProto: MessageTypeDefinition
    AnyASTCreateStatementProto: MessageTypeDefinition
    AnyASTCreateTableStmtBaseProto: MessageTypeDefinition
    AnyASTCreateViewStatementBaseProto: MessageTypeDefinition
    AnyASTDdlStatementProto: MessageTypeDefinition
    AnyASTElementTypeColumnSchemaProto: MessageTypeDefinition
    AnyASTExpressionProto: MessageTypeDefinition
    AnyASTGeneralizedPathExpressionProto: MessageTypeDefinition
    AnyASTLeafProto: MessageTypeDefinition
    AnyASTLoopStatementProto: MessageTypeDefinition
    AnyASTNodeProto: MessageTypeDefinition
    AnyASTParameterExprBaseProto: MessageTypeDefinition
    AnyASTQueryExpressionProto: MessageTypeDefinition
    AnyASTScriptStatementProto: MessageTypeDefinition
    AnyASTStatementProto: MessageTypeDefinition
    AnyASTTableConstraintProto: MessageTypeDefinition
    AnyASTTableDataSourceProto: MessageTypeDefinition
    AnyASTTableElementProto: MessageTypeDefinition
    AnyASTTableExpressionProto: MessageTypeDefinition
    AnyASTTransactionModeProto: MessageTypeDefinition
    AnyASTTypeProto: MessageTypeDefinition
    AnyResolvedAggregateScanBaseProto: MessageTypeDefinition
    AnyResolvedAlterActionProto: MessageTypeDefinition
    AnyResolvedAlterColumnActionProto: MessageTypeDefinition
    AnyResolvedAlterObjectStmtProto: MessageTypeDefinition
    AnyResolvedArgumentProto: MessageTypeDefinition
    AnyResolvedConstraintProto: MessageTypeDefinition
    AnyResolvedCreateStatementProto: MessageTypeDefinition
    AnyResolvedCreateTableStmtBaseProto: MessageTypeDefinition
    AnyResolvedCreateViewBaseProto: MessageTypeDefinition
    AnyResolvedExprProto: MessageTypeDefinition
    AnyResolvedFunctionCallBaseProto: MessageTypeDefinition
    AnyResolvedGrantOrRevokeStmtProto: MessageTypeDefinition
    AnyResolvedGroupingSetBaseProto: MessageTypeDefinition
    AnyResolvedNodeProto: MessageTypeDefinition
    AnyResolvedNonScalarFunctionCallBaseProto: MessageTypeDefinition
    AnyResolvedScanProto: MessageTypeDefinition
    AnyResolvedStatementProto: MessageTypeDefinition
    ArgumentTypeLambdaProto: MessageTypeDefinition
    ArrayTypeProto: MessageTypeDefinition
    CollationProto: MessageTypeDefinition
    ColumnRefProto: MessageTypeDefinition
    ConnectionRefProto: MessageTypeDefinition
    ConstantRefProto: MessageTypeDefinition
    DeprecatedEncoding: MessageTypeDefinition
    DeprecationWarning: MessageTypeDefinition
    EnabledRewriteProto: MessageTypeDefinition
    EnumTypeProto: MessageTypeDefinition
    ErrorLocation: MessageTypeDefinition
    ErrorMessageMode: EnumTypeDefinition
    ErrorMessageModeForPayload: MessageTypeDefinition
    ErrorSource: MessageTypeDefinition
    ExpressionAttributeProto: MessageTypeDefinition
    ExtendedTypeParametersProto: MessageTypeDefinition
    FieldDescriptorRefProto: MessageTypeDefinition
    FieldFormat: MessageTypeDefinition
    FormatterOptionsProto: MessageTypeDefinition
    FormatterRangeProto: MessageTypeDefinition
    FreestandingDeprecationWarning: MessageTypeDefinition
    FunctionArgumentTypeOptionsProto: MessageTypeDefinition
    FunctionArgumentTypeProto: MessageTypeDefinition
    FunctionEnums: MessageTypeDefinition
    FunctionOptionsProto: MessageTypeDefinition
    FunctionProto: MessageTypeDefinition
    FunctionRefProto: MessageTypeDefinition
    FunctionSignatureId: EnumTypeDefinition
    FunctionSignatureOptionsProto: MessageTypeDefinition
    FunctionSignatureProto: MessageTypeDefinition
    FunctionSignatureRewriteOptionsProto: MessageTypeDefinition
    GroupingSetRewriteOptions: MessageTypeDefinition
    LanguageFeature: EnumTypeDefinition
    LanguageFeatureOptions: MessageTypeDefinition
    LanguageOptionsProto: MessageTypeDefinition
    LanguageVersion: EnumTypeDefinition
    ModelRefProto: MessageTypeDefinition
    NameResolutionMode: EnumTypeDefinition
    NumericTypeParametersProto: MessageTypeDefinition
    OneofDescriptorRefProto: MessageTypeDefinition
    OpaqueEnumTypeOptions: MessageTypeDefinition
    OpaqueEnumValueOptions: MessageTypeDefinition
    ParameterMode: EnumTypeDefinition
    ParseLocationRangeProto: MessageTypeDefinition
    ParseLocationRecordType: EnumTypeDefinition
    ParseResumeLocationProto: MessageTypeDefinition
    ProcedureProto: MessageTypeDefinition
    ProcedureRefProto: MessageTypeDefinition
    ProductMode: EnumTypeDefinition
    ProtoTypeProto: MessageTypeDefinition
    RangeTypeProto: MessageTypeDefinition
    ResolvedASTRewrite: EnumTypeDefinition
    ResolvedASTRewriteOptions: MessageTypeDefinition
    ResolvedAbortBatchStmtProto: MessageTypeDefinition
    ResolvedAddColumnActionProto: MessageTypeDefinition
    ResolvedAddConstraintActionProto: MessageTypeDefinition
    ResolvedAddSubEntityActionProto: MessageTypeDefinition
    ResolvedAddToRestricteeListActionProto: MessageTypeDefinition
    ResolvedAggregateFunctionCallProto: MessageTypeDefinition
    ResolvedAggregateHavingModifierEnums: MessageTypeDefinition
    ResolvedAggregateHavingModifierProto: MessageTypeDefinition
    ResolvedAggregateScanBaseProto: MessageTypeDefinition
    ResolvedAggregateScanProto: MessageTypeDefinition
    ResolvedAggregationThresholdAggregateScanProto: MessageTypeDefinition
    ResolvedAlterActionProto: MessageTypeDefinition
    ResolvedAlterAllRowAccessPoliciesStmtProto: MessageTypeDefinition
    ResolvedAlterApproxViewStmtProto: MessageTypeDefinition
    ResolvedAlterColumnActionProto: MessageTypeDefinition
    ResolvedAlterColumnDropDefaultActionProto: MessageTypeDefinition
    ResolvedAlterColumnDropNotNullActionProto: MessageTypeDefinition
    ResolvedAlterColumnOptionsActionProto: MessageTypeDefinition
    ResolvedAlterColumnSetDataTypeActionProto: MessageTypeDefinition
    ResolvedAlterColumnSetDefaultActionProto: MessageTypeDefinition
    ResolvedAlterDatabaseStmtProto: MessageTypeDefinition
    ResolvedAlterEntityStmtProto: MessageTypeDefinition
    ResolvedAlterMaterializedViewStmtProto: MessageTypeDefinition
    ResolvedAlterModelStmtProto: MessageTypeDefinition
    ResolvedAlterObjectStmtProto: MessageTypeDefinition
    ResolvedAlterPrivilegeRestrictionStmtProto: MessageTypeDefinition
    ResolvedAlterRowAccessPolicyStmtProto: MessageTypeDefinition
    ResolvedAlterSchemaStmtProto: MessageTypeDefinition
    ResolvedAlterSubEntityActionProto: MessageTypeDefinition
    ResolvedAlterTableSetOptionsStmtProto: MessageTypeDefinition
    ResolvedAlterTableStmtProto: MessageTypeDefinition
    ResolvedAlterViewStmtProto: MessageTypeDefinition
    ResolvedAnalyticFunctionCallProto: MessageTypeDefinition
    ResolvedAnalyticFunctionGroupProto: MessageTypeDefinition
    ResolvedAnalyticScanProto: MessageTypeDefinition
    ResolvedAnalyzeStmtProto: MessageTypeDefinition
    ResolvedAnonymizedAggregateScanProto: MessageTypeDefinition
    ResolvedArgumentDefEnums: MessageTypeDefinition
    ResolvedArgumentDefProto: MessageTypeDefinition
    ResolvedArgumentListProto: MessageTypeDefinition
    ResolvedArgumentProto: MessageTypeDefinition
    ResolvedArgumentRefProto: MessageTypeDefinition
    ResolvedArrayScanProto: MessageTypeDefinition
    ResolvedAssertRowsModifiedProto: MessageTypeDefinition
    ResolvedAssertStmtProto: MessageTypeDefinition
    ResolvedAssignmentStmtProto: MessageTypeDefinition
    ResolvedAuxLoadDataPartitionFilterProto: MessageTypeDefinition
    ResolvedAuxLoadDataStmtEnums: MessageTypeDefinition
    ResolvedAuxLoadDataStmtProto: MessageTypeDefinition
    ResolvedBeginStmtEnums: MessageTypeDefinition
    ResolvedBeginStmtProto: MessageTypeDefinition
    ResolvedCallStmtProto: MessageTypeDefinition
    ResolvedCastProto: MessageTypeDefinition
    ResolvedCatalogColumnRefProto: MessageTypeDefinition
    ResolvedCheckConstraintProto: MessageTypeDefinition
    ResolvedCloneDataStmtProto: MessageTypeDefinition
    ResolvedCollationProto: MessageTypeDefinition
    ResolvedColumnAnnotationsProto: MessageTypeDefinition
    ResolvedColumnDefaultValueProto: MessageTypeDefinition
    ResolvedColumnDefinitionProto: MessageTypeDefinition
    ResolvedColumnHolderProto: MessageTypeDefinition
    ResolvedColumnProto: MessageTypeDefinition
    ResolvedColumnRefProto: MessageTypeDefinition
    ResolvedCommitStmtProto: MessageTypeDefinition
    ResolvedComputedColumnProto: MessageTypeDefinition
    ResolvedConnectionProto: MessageTypeDefinition
    ResolvedConstantProto: MessageTypeDefinition
    ResolvedConstraintProto: MessageTypeDefinition
    ResolvedCreateApproxViewStmtProto: MessageTypeDefinition
    ResolvedCreateConstantStmtProto: MessageTypeDefinition
    ResolvedCreateDatabaseStmtProto: MessageTypeDefinition
    ResolvedCreateEntityStmtProto: MessageTypeDefinition
    ResolvedCreateExternalTableStmtProto: MessageTypeDefinition
    ResolvedCreateFunctionStmtProto: MessageTypeDefinition
    ResolvedCreateIndexStmtProto: MessageTypeDefinition
    ResolvedCreateMaterializedViewStmtProto: MessageTypeDefinition
    ResolvedCreateModelAliasedQueryProto: MessageTypeDefinition
    ResolvedCreateModelStmtProto: MessageTypeDefinition
    ResolvedCreatePrivilegeRestrictionStmtProto: MessageTypeDefinition
    ResolvedCreateProcedureStmtProto: MessageTypeDefinition
    ResolvedCreateRowAccessPolicyStmtProto: MessageTypeDefinition
    ResolvedCreateSchemaStmtProto: MessageTypeDefinition
    ResolvedCreateSnapshotTableStmtProto: MessageTypeDefinition
    ResolvedCreateStatementEnums: MessageTypeDefinition
    ResolvedCreateStatementProto: MessageTypeDefinition
    ResolvedCreateTableAsSelectStmtProto: MessageTypeDefinition
    ResolvedCreateTableFunctionStmtProto: MessageTypeDefinition
    ResolvedCreateTableStmtBaseProto: MessageTypeDefinition
    ResolvedCreateTableStmtProto: MessageTypeDefinition
    ResolvedCreateViewBaseProto: MessageTypeDefinition
    ResolvedCreateViewStmtProto: MessageTypeDefinition
    ResolvedCubeProto: MessageTypeDefinition
    ResolvedDMLDefaultProto: MessageTypeDefinition
    ResolvedDMLValueProto: MessageTypeDefinition
    ResolvedDefineTableStmtProto: MessageTypeDefinition
    ResolvedDeleteStmtProto: MessageTypeDefinition
    ResolvedDescribeStmtProto: MessageTypeDefinition
    ResolvedDescriptorProto: MessageTypeDefinition
    ResolvedDifferentialPrivacyAggregateScanProto: MessageTypeDefinition
    ResolvedDropColumnActionProto: MessageTypeDefinition
    ResolvedDropConstraintActionProto: MessageTypeDefinition
    ResolvedDropFunctionStmtProto: MessageTypeDefinition
    ResolvedDropMaterializedViewStmtProto: MessageTypeDefinition
    ResolvedDropPrimaryKeyActionProto: MessageTypeDefinition
    ResolvedDropPrivilegeRestrictionStmtProto: MessageTypeDefinition
    ResolvedDropRowAccessPolicyStmtProto: MessageTypeDefinition
    ResolvedDropSearchIndexStmtProto: MessageTypeDefinition
    ResolvedDropSnapshotTableStmtProto: MessageTypeDefinition
    ResolvedDropStmtEnums: MessageTypeDefinition
    ResolvedDropStmtProto: MessageTypeDefinition
    ResolvedDropSubEntityActionProto: MessageTypeDefinition
    ResolvedDropTableFunctionStmtProto: MessageTypeDefinition
    ResolvedExecuteAsRoleScanProto: MessageTypeDefinition
    ResolvedExecuteImmediateArgumentProto: MessageTypeDefinition
    ResolvedExecuteImmediateStmtProto: MessageTypeDefinition
    ResolvedExplainStmtProto: MessageTypeDefinition
    ResolvedExportDataStmtProto: MessageTypeDefinition
    ResolvedExportMetadataStmtProto: MessageTypeDefinition
    ResolvedExportModelStmtProto: MessageTypeDefinition
    ResolvedExprProto: MessageTypeDefinition
    ResolvedExpressionColumnProto: MessageTypeDefinition
    ResolvedExtendedCastElementProto: MessageTypeDefinition
    ResolvedExtendedCastProto: MessageTypeDefinition
    ResolvedFilterFieldArgProto: MessageTypeDefinition
    ResolvedFilterFieldProto: MessageTypeDefinition
    ResolvedFilterScanProto: MessageTypeDefinition
    ResolvedFilterUsingActionProto: MessageTypeDefinition
    ResolvedFlattenProto: MessageTypeDefinition
    ResolvedFlattenedArgProto: MessageTypeDefinition
    ResolvedForeignKeyEnums: MessageTypeDefinition
    ResolvedForeignKeyProto: MessageTypeDefinition
    ResolvedFunctionArgumentProto: MessageTypeDefinition
    ResolvedFunctionCallBaseEnums: MessageTypeDefinition
    ResolvedFunctionCallBaseProto: MessageTypeDefinition
    ResolvedFunctionCallInfoProto: MessageTypeDefinition
    ResolvedFunctionCallProto: MessageTypeDefinition
    ResolvedFunctionSignatureHolderProto: MessageTypeDefinition
    ResolvedGeneratedColumnInfoEnums: MessageTypeDefinition
    ResolvedGeneratedColumnInfoProto: MessageTypeDefinition
    ResolvedGetJsonFieldProto: MessageTypeDefinition
    ResolvedGetProtoFieldProto: MessageTypeDefinition
    ResolvedGetStructFieldProto: MessageTypeDefinition
    ResolvedGrantOrRevokeStmtProto: MessageTypeDefinition
    ResolvedGrantStmtProto: MessageTypeDefinition
    ResolvedGrantToActionProto: MessageTypeDefinition
    ResolvedGroupRowsScanProto: MessageTypeDefinition
    ResolvedGroupingCallProto: MessageTypeDefinition
    ResolvedGroupingSetBaseProto: MessageTypeDefinition
    ResolvedGroupingSetMultiColumnProto: MessageTypeDefinition
    ResolvedGroupingSetProto: MessageTypeDefinition
    ResolvedImportStmtEnums: MessageTypeDefinition
    ResolvedImportStmtProto: MessageTypeDefinition
    ResolvedIndexItemProto: MessageTypeDefinition
    ResolvedInlineLambdaProto: MessageTypeDefinition
    ResolvedInsertRowProto: MessageTypeDefinition
    ResolvedInsertStmtEnums: MessageTypeDefinition
    ResolvedInsertStmtProto: MessageTypeDefinition
    ResolvedJoinScanEnums: MessageTypeDefinition
    ResolvedJoinScanProto: MessageTypeDefinition
    ResolvedLimitOffsetScanProto: MessageTypeDefinition
    ResolvedLiteralProto: MessageTypeDefinition
    ResolvedMakeProtoFieldProto: MessageTypeDefinition
    ResolvedMakeProtoProto: MessageTypeDefinition
    ResolvedMakeStructProto: MessageTypeDefinition
    ResolvedMergeStmtProto: MessageTypeDefinition
    ResolvedMergeWhenEnums: MessageTypeDefinition
    ResolvedMergeWhenProto: MessageTypeDefinition
    ResolvedModelProto: MessageTypeDefinition
    ResolvedModuleStmtProto: MessageTypeDefinition
    ResolvedNodeKind: EnumTypeDefinition
    ResolvedNodeProto: MessageTypeDefinition
    ResolvedNonScalarFunctionCallBaseEnums: MessageTypeDefinition
    ResolvedNonScalarFunctionCallBaseProto: MessageTypeDefinition
    ResolvedObjectUnitProto: MessageTypeDefinition
    ResolvedOptionProto: MessageTypeDefinition
    ResolvedOrderByItemEnums: MessageTypeDefinition
    ResolvedOrderByItemProto: MessageTypeDefinition
    ResolvedOrderByScanProto: MessageTypeDefinition
    ResolvedOutputColumnProto: MessageTypeDefinition
    ResolvedParameterProto: MessageTypeDefinition
    ResolvedPivotColumnProto: MessageTypeDefinition
    ResolvedPivotScanProto: MessageTypeDefinition
    ResolvedPrimaryKeyProto: MessageTypeDefinition
    ResolvedPrivilegeProto: MessageTypeDefinition
    ResolvedProjectScanProto: MessageTypeDefinition
    ResolvedQueryStmtProto: MessageTypeDefinition
    ResolvedRecursiveRefScanProto: MessageTypeDefinition
    ResolvedRecursiveScanEnums: MessageTypeDefinition
    ResolvedRecursiveScanProto: MessageTypeDefinition
    ResolvedRelationArgumentScanProto: MessageTypeDefinition
    ResolvedRemoveFromRestricteeListActionProto: MessageTypeDefinition
    ResolvedRenameColumnActionProto: MessageTypeDefinition
    ResolvedRenameStmtProto: MessageTypeDefinition
    ResolvedRenameToActionProto: MessageTypeDefinition
    ResolvedReplaceFieldItemProto: MessageTypeDefinition
    ResolvedReplaceFieldProto: MessageTypeDefinition
    ResolvedRestrictToActionProto: MessageTypeDefinition
    ResolvedReturningClauseProto: MessageTypeDefinition
    ResolvedRevokeFromActionProto: MessageTypeDefinition
    ResolvedRevokeStmtProto: MessageTypeDefinition
    ResolvedRollbackStmtProto: MessageTypeDefinition
    ResolvedRollupProto: MessageTypeDefinition
    ResolvedRunBatchStmtProto: MessageTypeDefinition
    ResolvedSampleScanEnums: MessageTypeDefinition
    ResolvedSampleScanProto: MessageTypeDefinition
    ResolvedScanProto: MessageTypeDefinition
    ResolvedSequenceProto: MessageTypeDefinition
    ResolvedSetAsActionProto: MessageTypeDefinition
    ResolvedSetCollateClauseProto: MessageTypeDefinition
    ResolvedSetOperationItemProto: MessageTypeDefinition
    ResolvedSetOperationScanEnums: MessageTypeDefinition
    ResolvedSetOperationScanProto: MessageTypeDefinition
    ResolvedSetOptionsActionProto: MessageTypeDefinition
    ResolvedSetTransactionStmtProto: MessageTypeDefinition
    ResolvedShowStmtProto: MessageTypeDefinition
    ResolvedSingleRowScanProto: MessageTypeDefinition
    ResolvedStartBatchStmtProto: MessageTypeDefinition
    ResolvedStatementEnums: MessageTypeDefinition
    ResolvedStatementProto: MessageTypeDefinition
    ResolvedSubqueryExprEnums: MessageTypeDefinition
    ResolvedSubqueryExprProto: MessageTypeDefinition
    ResolvedSystemVariableProto: MessageTypeDefinition
    ResolvedTVFScanProto: MessageTypeDefinition
    ResolvedTableAndColumnInfoProto: MessageTypeDefinition
    ResolvedTableScanProto: MessageTypeDefinition
    ResolvedTruncateStmtProto: MessageTypeDefinition
    ResolvedUndropStmtProto: MessageTypeDefinition
    ResolvedUnnestItemProto: MessageTypeDefinition
    ResolvedUnpivotArgProto: MessageTypeDefinition
    ResolvedUnpivotScanProto: MessageTypeDefinition
    ResolvedUpdateArrayItemProto: MessageTypeDefinition
    ResolvedUpdateItemProto: MessageTypeDefinition
    ResolvedUpdateStmtProto: MessageTypeDefinition
    ResolvedWindowFrameEnums: MessageTypeDefinition
    ResolvedWindowFrameExprEnums: MessageTypeDefinition
    ResolvedWindowFrameExprProto: MessageTypeDefinition
    ResolvedWindowFrameProto: MessageTypeDefinition
    ResolvedWindowOrderingProto: MessageTypeDefinition
    ResolvedWindowPartitioningProto: MessageTypeDefinition
    ResolvedWithEntryProto: MessageTypeDefinition
    ResolvedWithExprProto: MessageTypeDefinition
    ResolvedWithPartitionColumnsProto: MessageTypeDefinition
    ResolvedWithRefScanProto: MessageTypeDefinition
    ResolvedWithScanProto: MessageTypeDefinition
    RewriteOptions: MessageTypeDefinition
    SchemaObjectKind: EnumTypeDefinition
    SequenceRefProto: MessageTypeDefinition
    SignatureArgumentKind: EnumTypeDefinition
    SimpleAnonymizationInfoProto: MessageTypeDefinition
    SimpleCatalogProto: MessageTypeDefinition
    SimpleColumnProto: MessageTypeDefinition
    SimpleConnectionProto: MessageTypeDefinition
    SimpleConstantProto: MessageTypeDefinition
    SimpleModelProto: MessageTypeDefinition
    SimpleTableProto: MessageTypeDefinition
    SimpleValueProto: MessageTypeDefinition
    StatementContext: EnumTypeDefinition
    StringTypeParametersProto: MessageTypeDefinition
    StructFieldProto: MessageTypeDefinition
    StructTypeProto: MessageTypeDefinition
    TVFArgumentProto: MessageTypeDefinition
    TVFConnectionProto: MessageTypeDefinition
    TVFDescriptorProto: MessageTypeDefinition
    TVFModelProto: MessageTypeDefinition
    TVFRelationColumnProto: MessageTypeDefinition
    TVFRelationProto: MessageTypeDefinition
    TVFSignatureOptionsProto: MessageTypeDefinition
    TVFSignatureProto: MessageTypeDefinition
    TableRefProto: MessageTypeDefinition
    TableValuedFunctionOptionsProto: MessageTypeDefinition
    TableValuedFunctionProto: MessageTypeDefinition
    TableValuedFunctionRefProto: MessageTypeDefinition
    TypeKind: EnumTypeDefinition
    TypeModifiersProto: MessageTypeDefinition
    TypeParametersProto: MessageTypeDefinition
    TypeProto: MessageTypeDefinition
    ValueProto: MessageTypeDefinition
    ValueWithTypeProto: MessageTypeDefinition
    ZetaSQLBuiltinFunctionOptionsProto: MessageTypeDefinition
    local_service: {
      AnalyzeRequest: MessageTypeDefinition
      AnalyzeResponse: MessageTypeDefinition
      AnalyzerOptionsRequest: MessageTypeDefinition
      BuildSqlRequest: MessageTypeDefinition
      BuildSqlResponse: MessageTypeDefinition
      DescriptorPoolIdList: MessageTypeDefinition
      DescriptorPoolListProto: MessageTypeDefinition
      EvaluateModifyBatchRequest: MessageTypeDefinition
      EvaluateModifyBatchResponse: MessageTypeDefinition
      EvaluateModifyRequest: MessageTypeDefinition
      EvaluateModifyResponse: MessageTypeDefinition
      EvaluateQueryBatchRequest: MessageTypeDefinition
      EvaluateQueryBatchResponse: MessageTypeDefinition
      EvaluateQueryRequest: MessageTypeDefinition
      EvaluateQueryResponse: MessageTypeDefinition
      EvaluateRequest: MessageTypeDefinition
      EvaluateRequestBatch: MessageTypeDefinition
      EvaluateResponse: MessageTypeDefinition
      EvaluateResponseBatch: MessageTypeDefinition
      ExtractTableNamesFromNextStatementRequest: MessageTypeDefinition
      ExtractTableNamesFromNextStatementResponse: MessageTypeDefinition
      ExtractTableNamesFromStatementRequest: MessageTypeDefinition
      ExtractTableNamesFromStatementResponse: MessageTypeDefinition
      FormatSqlRequest: MessageTypeDefinition
      FormatSqlResponse: MessageTypeDefinition
      GetBuiltinFunctionsResponse: MessageTypeDefinition
      LanguageOptionsRequest: MessageTypeDefinition
      Parameter: MessageTypeDefinition
      ParseRequest: MessageTypeDefinition
      ParseResponse: MessageTypeDefinition
      PrepareModifyRequest: MessageTypeDefinition
      PrepareModifyResponse: MessageTypeDefinition
      PrepareQueryRequest: MessageTypeDefinition
      PrepareQueryResponse: MessageTypeDefinition
      PrepareRequest: MessageTypeDefinition
      PrepareResponse: MessageTypeDefinition
      PreparedModifyState: MessageTypeDefinition
      PreparedQueryState: MessageTypeDefinition
      PreparedState: MessageTypeDefinition
      RegisterCatalogRequest: MessageTypeDefinition
      RegisterResponse: MessageTypeDefinition
      TableContent: MessageTypeDefinition
      TableData: MessageTypeDefinition
      TableFromProtoRequest: MessageTypeDefinition
      UnprepareModifyRequest: MessageTypeDefinition
      UnprepareQueryRequest: MessageTypeDefinition
      UnprepareRequest: MessageTypeDefinition
      UnregisterRequest: MessageTypeDefinition
      ZetaSqlLocalService: SubtypeConstructor<typeof grpc.Client, _zetasql_local_service_ZetaSqlLocalServiceClient> & { service: _zetasql_local_service_ZetaSqlLocalServiceDefinition }
    }
  }
}

