// Original file: src/zetasql/protos/zetasql/resolved_ast/resolved_ast.proto

import type { ResolvedMakeProtoFieldProto as _zetasql_ResolvedMakeProtoFieldProto, ResolvedMakeProtoFieldProto__Output as _zetasql_ResolvedMakeProtoFieldProto__Output } from '../zetasql/ResolvedMakeProtoFieldProto';
import type { ResolvedColumnHolderProto as _zetasql_ResolvedColumnHolderProto, ResolvedColumnHolderProto__Output as _zetasql_ResolvedColumnHolderProto__Output } from '../zetasql/ResolvedColumnHolderProto';
import type { ResolvedComputedColumnProto as _zetasql_ResolvedComputedColumnProto, ResolvedComputedColumnProto__Output as _zetasql_ResolvedComputedColumnProto__Output } from '../zetasql/ResolvedComputedColumnProto';
import type { ResolvedOrderByItemProto as _zetasql_ResolvedOrderByItemProto, ResolvedOrderByItemProto__Output as _zetasql_ResolvedOrderByItemProto__Output } from '../zetasql/ResolvedOrderByItemProto';
import type { ResolvedOutputColumnProto as _zetasql_ResolvedOutputColumnProto, ResolvedOutputColumnProto__Output as _zetasql_ResolvedOutputColumnProto__Output } from '../zetasql/ResolvedOutputColumnProto';
import type { ResolvedWithEntryProto as _zetasql_ResolvedWithEntryProto, ResolvedWithEntryProto__Output as _zetasql_ResolvedWithEntryProto__Output } from '../zetasql/ResolvedWithEntryProto';
import type { ResolvedOptionProto as _zetasql_ResolvedOptionProto, ResolvedOptionProto__Output as _zetasql_ResolvedOptionProto__Output } from '../zetasql/ResolvedOptionProto';
import type { ResolvedWindowPartitioningProto as _zetasql_ResolvedWindowPartitioningProto, ResolvedWindowPartitioningProto__Output as _zetasql_ResolvedWindowPartitioningProto__Output } from '../zetasql/ResolvedWindowPartitioningProto';
import type { ResolvedWindowOrderingProto as _zetasql_ResolvedWindowOrderingProto, ResolvedWindowOrderingProto__Output as _zetasql_ResolvedWindowOrderingProto__Output } from '../zetasql/ResolvedWindowOrderingProto';
import type { ResolvedWindowFrameProto as _zetasql_ResolvedWindowFrameProto, ResolvedWindowFrameProto__Output as _zetasql_ResolvedWindowFrameProto__Output } from '../zetasql/ResolvedWindowFrameProto';
import type { ResolvedAnalyticFunctionGroupProto as _zetasql_ResolvedAnalyticFunctionGroupProto, ResolvedAnalyticFunctionGroupProto__Output as _zetasql_ResolvedAnalyticFunctionGroupProto__Output } from '../zetasql/ResolvedAnalyticFunctionGroupProto';
import type { ResolvedWindowFrameExprProto as _zetasql_ResolvedWindowFrameExprProto, ResolvedWindowFrameExprProto__Output as _zetasql_ResolvedWindowFrameExprProto__Output } from '../zetasql/ResolvedWindowFrameExprProto';
import type { ResolvedDMLValueProto as _zetasql_ResolvedDMLValueProto, ResolvedDMLValueProto__Output as _zetasql_ResolvedDMLValueProto__Output } from '../zetasql/ResolvedDMLValueProto';
import type { ResolvedAssertRowsModifiedProto as _zetasql_ResolvedAssertRowsModifiedProto, ResolvedAssertRowsModifiedProto__Output as _zetasql_ResolvedAssertRowsModifiedProto__Output } from '../zetasql/ResolvedAssertRowsModifiedProto';
import type { ResolvedInsertRowProto as _zetasql_ResolvedInsertRowProto, ResolvedInsertRowProto__Output as _zetasql_ResolvedInsertRowProto__Output } from '../zetasql/ResolvedInsertRowProto';
import type { ResolvedUpdateItemProto as _zetasql_ResolvedUpdateItemProto, ResolvedUpdateItemProto__Output as _zetasql_ResolvedUpdateItemProto__Output } from '../zetasql/ResolvedUpdateItemProto';
import type { ResolvedPrivilegeProto as _zetasql_ResolvedPrivilegeProto, ResolvedPrivilegeProto__Output as _zetasql_ResolvedPrivilegeProto__Output } from '../zetasql/ResolvedPrivilegeProto';
import type { ResolvedArgumentDefProto as _zetasql_ResolvedArgumentDefProto, ResolvedArgumentDefProto__Output as _zetasql_ResolvedArgumentDefProto__Output } from '../zetasql/ResolvedArgumentDefProto';
import type { ResolvedArgumentListProto as _zetasql_ResolvedArgumentListProto, ResolvedArgumentListProto__Output as _zetasql_ResolvedArgumentListProto__Output } from '../zetasql/ResolvedArgumentListProto';
import type { ResolvedFunctionArgumentProto as _zetasql_ResolvedFunctionArgumentProto, ResolvedFunctionArgumentProto__Output as _zetasql_ResolvedFunctionArgumentProto__Output } from '../zetasql/ResolvedFunctionArgumentProto';
import type { ResolvedFunctionSignatureHolderProto as _zetasql_ResolvedFunctionSignatureHolderProto, ResolvedFunctionSignatureHolderProto__Output as _zetasql_ResolvedFunctionSignatureHolderProto__Output } from '../zetasql/ResolvedFunctionSignatureHolderProto';
import type { ResolvedAggregateHavingModifierProto as _zetasql_ResolvedAggregateHavingModifierProto, ResolvedAggregateHavingModifierProto__Output as _zetasql_ResolvedAggregateHavingModifierProto__Output } from '../zetasql/ResolvedAggregateHavingModifierProto';
import type { ResolvedColumnDefinitionProto as _zetasql_ResolvedColumnDefinitionProto, ResolvedColumnDefinitionProto__Output as _zetasql_ResolvedColumnDefinitionProto__Output } from '../zetasql/ResolvedColumnDefinitionProto';
import type { ResolvedGroupingSetProto as _zetasql_ResolvedGroupingSetProto, ResolvedGroupingSetProto__Output as _zetasql_ResolvedGroupingSetProto__Output } from '../zetasql/ResolvedGroupingSetProto';
import type { ResolvedSetOperationItemProto as _zetasql_ResolvedSetOperationItemProto, ResolvedSetOperationItemProto__Output as _zetasql_ResolvedSetOperationItemProto__Output } from '../zetasql/ResolvedSetOperationItemProto';
import type { ResolvedIndexItemProto as _zetasql_ResolvedIndexItemProto, ResolvedIndexItemProto__Output as _zetasql_ResolvedIndexItemProto__Output } from '../zetasql/ResolvedIndexItemProto';
import type { ResolvedMergeWhenProto as _zetasql_ResolvedMergeWhenProto, ResolvedMergeWhenProto__Output as _zetasql_ResolvedMergeWhenProto__Output } from '../zetasql/ResolvedMergeWhenProto';
import type { ResolvedUpdateArrayItemProto as _zetasql_ResolvedUpdateArrayItemProto, ResolvedUpdateArrayItemProto__Output as _zetasql_ResolvedUpdateArrayItemProto__Output } from '../zetasql/ResolvedUpdateArrayItemProto';
import type { ResolvedColumnAnnotationsProto as _zetasql_ResolvedColumnAnnotationsProto, ResolvedColumnAnnotationsProto__Output as _zetasql_ResolvedColumnAnnotationsProto__Output } from '../zetasql/ResolvedColumnAnnotationsProto';
import type { ResolvedGeneratedColumnInfoProto as _zetasql_ResolvedGeneratedColumnInfoProto, ResolvedGeneratedColumnInfoProto__Output as _zetasql_ResolvedGeneratedColumnInfoProto__Output } from '../zetasql/ResolvedGeneratedColumnInfoProto';
import type { ResolvedModelProto as _zetasql_ResolvedModelProto, ResolvedModelProto__Output as _zetasql_ResolvedModelProto__Output } from '../zetasql/ResolvedModelProto';
import type { AnyResolvedAlterActionProto as _zetasql_AnyResolvedAlterActionProto, AnyResolvedAlterActionProto__Output as _zetasql_AnyResolvedAlterActionProto__Output } from '../zetasql/AnyResolvedAlterActionProto';
import type { ResolvedUnnestItemProto as _zetasql_ResolvedUnnestItemProto, ResolvedUnnestItemProto__Output as _zetasql_ResolvedUnnestItemProto__Output } from '../zetasql/ResolvedUnnestItemProto';
import type { ResolvedReplaceFieldItemProto as _zetasql_ResolvedReplaceFieldItemProto, ResolvedReplaceFieldItemProto__Output as _zetasql_ResolvedReplaceFieldItemProto__Output } from '../zetasql/ResolvedReplaceFieldItemProto';
import type { ResolvedConnectionProto as _zetasql_ResolvedConnectionProto, ResolvedConnectionProto__Output as _zetasql_ResolvedConnectionProto__Output } from '../zetasql/ResolvedConnectionProto';
import type { ResolvedExecuteImmediateArgumentProto as _zetasql_ResolvedExecuteImmediateArgumentProto, ResolvedExecuteImmediateArgumentProto__Output as _zetasql_ResolvedExecuteImmediateArgumentProto__Output } from '../zetasql/ResolvedExecuteImmediateArgumentProto';
import type { ResolvedDescriptorProto as _zetasql_ResolvedDescriptorProto, ResolvedDescriptorProto__Output as _zetasql_ResolvedDescriptorProto__Output } from '../zetasql/ResolvedDescriptorProto';
import type { ResolvedExtendedCastElementProto as _zetasql_ResolvedExtendedCastElementProto, ResolvedExtendedCastElementProto__Output as _zetasql_ResolvedExtendedCastElementProto__Output } from '../zetasql/ResolvedExtendedCastElementProto';
import type { ResolvedWithPartitionColumnsProto as _zetasql_ResolvedWithPartitionColumnsProto, ResolvedWithPartitionColumnsProto__Output as _zetasql_ResolvedWithPartitionColumnsProto__Output } from '../zetasql/ResolvedWithPartitionColumnsProto';
import type { ResolvedExtendedCastProto as _zetasql_ResolvedExtendedCastProto, ResolvedExtendedCastProto__Output as _zetasql_ResolvedExtendedCastProto__Output } from '../zetasql/ResolvedExtendedCastProto';
import type { ResolvedInlineLambdaProto as _zetasql_ResolvedInlineLambdaProto, ResolvedInlineLambdaProto__Output as _zetasql_ResolvedInlineLambdaProto__Output } from '../zetasql/ResolvedInlineLambdaProto';
import type { AnyResolvedConstraintProto as _zetasql_AnyResolvedConstraintProto, AnyResolvedConstraintProto__Output as _zetasql_AnyResolvedConstraintProto__Output } from '../zetasql/AnyResolvedConstraintProto';
import type { ResolvedPivotColumnProto as _zetasql_ResolvedPivotColumnProto, ResolvedPivotColumnProto__Output as _zetasql_ResolvedPivotColumnProto__Output } from '../zetasql/ResolvedPivotColumnProto';
import type { ResolvedReturningClauseProto as _zetasql_ResolvedReturningClauseProto, ResolvedReturningClauseProto__Output as _zetasql_ResolvedReturningClauseProto__Output } from '../zetasql/ResolvedReturningClauseProto';
import type { ResolvedUnpivotArgProto as _zetasql_ResolvedUnpivotArgProto, ResolvedUnpivotArgProto__Output as _zetasql_ResolvedUnpivotArgProto__Output } from '../zetasql/ResolvedUnpivotArgProto';
import type { ResolvedFilterFieldArgProto as _zetasql_ResolvedFilterFieldArgProto, ResolvedFilterFieldArgProto__Output as _zetasql_ResolvedFilterFieldArgProto__Output } from '../zetasql/ResolvedFilterFieldArgProto';
import type { ResolvedTableAndColumnInfoProto as _zetasql_ResolvedTableAndColumnInfoProto, ResolvedTableAndColumnInfoProto__Output as _zetasql_ResolvedTableAndColumnInfoProto__Output } from '../zetasql/ResolvedTableAndColumnInfoProto';
import type { ResolvedColumnDefaultValueProto as _zetasql_ResolvedColumnDefaultValueProto, ResolvedColumnDefaultValueProto__Output as _zetasql_ResolvedColumnDefaultValueProto__Output } from '../zetasql/ResolvedColumnDefaultValueProto';
import type { ResolvedObjectUnitProto as _zetasql_ResolvedObjectUnitProto, ResolvedObjectUnitProto__Output as _zetasql_ResolvedObjectUnitProto__Output } from '../zetasql/ResolvedObjectUnitProto';
import type { ResolvedAuxLoadDataPartitionFilterProto as _zetasql_ResolvedAuxLoadDataPartitionFilterProto, ResolvedAuxLoadDataPartitionFilterProto__Output as _zetasql_ResolvedAuxLoadDataPartitionFilterProto__Output } from '../zetasql/ResolvedAuxLoadDataPartitionFilterProto';
import type { ResolvedCreateModelAliasedQueryProto as _zetasql_ResolvedCreateModelAliasedQueryProto, ResolvedCreateModelAliasedQueryProto__Output as _zetasql_ResolvedCreateModelAliasedQueryProto__Output } from '../zetasql/ResolvedCreateModelAliasedQueryProto';

export interface AnyResolvedArgumentProto {
  'resolvedMakeProtoFieldNode'?: (_zetasql_ResolvedMakeProtoFieldProto | null);
  'resolvedColumnHolderNode'?: (_zetasql_ResolvedColumnHolderProto | null);
  'resolvedComputedColumnNode'?: (_zetasql_ResolvedComputedColumnProto | null);
  'resolvedOrderByItemNode'?: (_zetasql_ResolvedOrderByItemProto | null);
  'resolvedOutputColumnNode'?: (_zetasql_ResolvedOutputColumnProto | null);
  'resolvedWithEntryNode'?: (_zetasql_ResolvedWithEntryProto | null);
  'resolvedOptionNode'?: (_zetasql_ResolvedOptionProto | null);
  'resolvedWindowPartitioningNode'?: (_zetasql_ResolvedWindowPartitioningProto | null);
  'resolvedWindowOrderingNode'?: (_zetasql_ResolvedWindowOrderingProto | null);
  'resolvedWindowFrameNode'?: (_zetasql_ResolvedWindowFrameProto | null);
  'resolvedAnalyticFunctionGroupNode'?: (_zetasql_ResolvedAnalyticFunctionGroupProto | null);
  'resolvedWindowFrameExprNode'?: (_zetasql_ResolvedWindowFrameExprProto | null);
  'resolvedDmlvalueNode'?: (_zetasql_ResolvedDMLValueProto | null);
  'resolvedAssertRowsModifiedNode'?: (_zetasql_ResolvedAssertRowsModifiedProto | null);
  'resolvedInsertRowNode'?: (_zetasql_ResolvedInsertRowProto | null);
  'resolvedUpdateItemNode'?: (_zetasql_ResolvedUpdateItemProto | null);
  'resolvedPrivilegeNode'?: (_zetasql_ResolvedPrivilegeProto | null);
  'resolvedArgumentDefNode'?: (_zetasql_ResolvedArgumentDefProto | null);
  'resolvedArgumentListNode'?: (_zetasql_ResolvedArgumentListProto | null);
  'resolvedFunctionArgumentNode'?: (_zetasql_ResolvedFunctionArgumentProto | null);
  'resolvedFunctionSignatureHolderNode'?: (_zetasql_ResolvedFunctionSignatureHolderProto | null);
  'resolvedAggregateHavingModifierNode'?: (_zetasql_ResolvedAggregateHavingModifierProto | null);
  'resolvedColumnDefinitionNode'?: (_zetasql_ResolvedColumnDefinitionProto | null);
  'resolvedGroupingSetNode'?: (_zetasql_ResolvedGroupingSetProto | null);
  'resolvedSetOperationItemNode'?: (_zetasql_ResolvedSetOperationItemProto | null);
  'resolvedIndexItemNode'?: (_zetasql_ResolvedIndexItemProto | null);
  'resolvedMergeWhenNode'?: (_zetasql_ResolvedMergeWhenProto | null);
  'resolvedUpdateArrayItemNode'?: (_zetasql_ResolvedUpdateArrayItemProto | null);
  'resolvedColumnAnnotationsNode'?: (_zetasql_ResolvedColumnAnnotationsProto | null);
  'resolvedGeneratedColumnInfoNode'?: (_zetasql_ResolvedGeneratedColumnInfoProto | null);
  'resolvedModelNode'?: (_zetasql_ResolvedModelProto | null);
  'resolvedAlterActionNode'?: (_zetasql_AnyResolvedAlterActionProto | null);
  'resolvedUnnestItemNode'?: (_zetasql_ResolvedUnnestItemProto | null);
  'resolvedReplaceFieldItemNode'?: (_zetasql_ResolvedReplaceFieldItemProto | null);
  'resolvedConnectionNode'?: (_zetasql_ResolvedConnectionProto | null);
  'resolvedExecuteImmediateArgumentNode'?: (_zetasql_ResolvedExecuteImmediateArgumentProto | null);
  'resolvedDescriptorNode'?: (_zetasql_ResolvedDescriptorProto | null);
  'resolvedExtendedCastElementNode'?: (_zetasql_ResolvedExtendedCastElementProto | null);
  'resolvedWithPartitionColumnsNode'?: (_zetasql_ResolvedWithPartitionColumnsProto | null);
  'resolvedExtendedCastNode'?: (_zetasql_ResolvedExtendedCastProto | null);
  'resolvedInlineLambdaNode'?: (_zetasql_ResolvedInlineLambdaProto | null);
  'resolvedConstraintNode'?: (_zetasql_AnyResolvedConstraintProto | null);
  'resolvedPivotColumnNode'?: (_zetasql_ResolvedPivotColumnProto | null);
  'resolvedReturningClauseNode'?: (_zetasql_ResolvedReturningClauseProto | null);
  'resolvedUnpivotArgNode'?: (_zetasql_ResolvedUnpivotArgProto | null);
  'resolvedFilterFieldArgNode'?: (_zetasql_ResolvedFilterFieldArgProto | null);
  'resolvedTableAndColumnInfoNode'?: (_zetasql_ResolvedTableAndColumnInfoProto | null);
  'resolvedColumnDefaultValueNode'?: (_zetasql_ResolvedColumnDefaultValueProto | null);
  'resolvedObjectUnitNode'?: (_zetasql_ResolvedObjectUnitProto | null);
  'resolvedAuxLoadDataPartitionFilterNode'?: (_zetasql_ResolvedAuxLoadDataPartitionFilterProto | null);
  'resolvedCreateModelAliasedQueryNode'?: (_zetasql_ResolvedCreateModelAliasedQueryProto | null);
  'node'?: "resolvedMakeProtoFieldNode"|"resolvedColumnHolderNode"|"resolvedComputedColumnNode"|"resolvedOrderByItemNode"|"resolvedOutputColumnNode"|"resolvedWithEntryNode"|"resolvedOptionNode"|"resolvedWindowPartitioningNode"|"resolvedWindowOrderingNode"|"resolvedWindowFrameNode"|"resolvedAnalyticFunctionGroupNode"|"resolvedWindowFrameExprNode"|"resolvedDmlvalueNode"|"resolvedAssertRowsModifiedNode"|"resolvedInsertRowNode"|"resolvedUpdateItemNode"|"resolvedPrivilegeNode"|"resolvedArgumentDefNode"|"resolvedArgumentListNode"|"resolvedFunctionArgumentNode"|"resolvedFunctionSignatureHolderNode"|"resolvedAggregateHavingModifierNode"|"resolvedColumnDefinitionNode"|"resolvedGroupingSetNode"|"resolvedSetOperationItemNode"|"resolvedIndexItemNode"|"resolvedMergeWhenNode"|"resolvedUpdateArrayItemNode"|"resolvedColumnAnnotationsNode"|"resolvedGeneratedColumnInfoNode"|"resolvedModelNode"|"resolvedAlterActionNode"|"resolvedUnnestItemNode"|"resolvedReplaceFieldItemNode"|"resolvedConnectionNode"|"resolvedExecuteImmediateArgumentNode"|"resolvedDescriptorNode"|"resolvedExtendedCastElementNode"|"resolvedWithPartitionColumnsNode"|"resolvedExtendedCastNode"|"resolvedInlineLambdaNode"|"resolvedConstraintNode"|"resolvedPivotColumnNode"|"resolvedReturningClauseNode"|"resolvedUnpivotArgNode"|"resolvedFilterFieldArgNode"|"resolvedTableAndColumnInfoNode"|"resolvedColumnDefaultValueNode"|"resolvedObjectUnitNode"|"resolvedAuxLoadDataPartitionFilterNode"|"resolvedCreateModelAliasedQueryNode";
}

export interface AnyResolvedArgumentProto__Output {
  'resolvedMakeProtoFieldNode'?: (_zetasql_ResolvedMakeProtoFieldProto__Output | null);
  'resolvedColumnHolderNode'?: (_zetasql_ResolvedColumnHolderProto__Output | null);
  'resolvedComputedColumnNode'?: (_zetasql_ResolvedComputedColumnProto__Output | null);
  'resolvedOrderByItemNode'?: (_zetasql_ResolvedOrderByItemProto__Output | null);
  'resolvedOutputColumnNode'?: (_zetasql_ResolvedOutputColumnProto__Output | null);
  'resolvedWithEntryNode'?: (_zetasql_ResolvedWithEntryProto__Output | null);
  'resolvedOptionNode'?: (_zetasql_ResolvedOptionProto__Output | null);
  'resolvedWindowPartitioningNode'?: (_zetasql_ResolvedWindowPartitioningProto__Output | null);
  'resolvedWindowOrderingNode'?: (_zetasql_ResolvedWindowOrderingProto__Output | null);
  'resolvedWindowFrameNode'?: (_zetasql_ResolvedWindowFrameProto__Output | null);
  'resolvedAnalyticFunctionGroupNode'?: (_zetasql_ResolvedAnalyticFunctionGroupProto__Output | null);
  'resolvedWindowFrameExprNode'?: (_zetasql_ResolvedWindowFrameExprProto__Output | null);
  'resolvedDmlvalueNode'?: (_zetasql_ResolvedDMLValueProto__Output | null);
  'resolvedAssertRowsModifiedNode'?: (_zetasql_ResolvedAssertRowsModifiedProto__Output | null);
  'resolvedInsertRowNode'?: (_zetasql_ResolvedInsertRowProto__Output | null);
  'resolvedUpdateItemNode'?: (_zetasql_ResolvedUpdateItemProto__Output | null);
  'resolvedPrivilegeNode'?: (_zetasql_ResolvedPrivilegeProto__Output | null);
  'resolvedArgumentDefNode'?: (_zetasql_ResolvedArgumentDefProto__Output | null);
  'resolvedArgumentListNode'?: (_zetasql_ResolvedArgumentListProto__Output | null);
  'resolvedFunctionArgumentNode'?: (_zetasql_ResolvedFunctionArgumentProto__Output | null);
  'resolvedFunctionSignatureHolderNode'?: (_zetasql_ResolvedFunctionSignatureHolderProto__Output | null);
  'resolvedAggregateHavingModifierNode'?: (_zetasql_ResolvedAggregateHavingModifierProto__Output | null);
  'resolvedColumnDefinitionNode'?: (_zetasql_ResolvedColumnDefinitionProto__Output | null);
  'resolvedGroupingSetNode'?: (_zetasql_ResolvedGroupingSetProto__Output | null);
  'resolvedSetOperationItemNode'?: (_zetasql_ResolvedSetOperationItemProto__Output | null);
  'resolvedIndexItemNode'?: (_zetasql_ResolvedIndexItemProto__Output | null);
  'resolvedMergeWhenNode'?: (_zetasql_ResolvedMergeWhenProto__Output | null);
  'resolvedUpdateArrayItemNode'?: (_zetasql_ResolvedUpdateArrayItemProto__Output | null);
  'resolvedColumnAnnotationsNode'?: (_zetasql_ResolvedColumnAnnotationsProto__Output | null);
  'resolvedGeneratedColumnInfoNode'?: (_zetasql_ResolvedGeneratedColumnInfoProto__Output | null);
  'resolvedModelNode'?: (_zetasql_ResolvedModelProto__Output | null);
  'resolvedAlterActionNode'?: (_zetasql_AnyResolvedAlterActionProto__Output | null);
  'resolvedUnnestItemNode'?: (_zetasql_ResolvedUnnestItemProto__Output | null);
  'resolvedReplaceFieldItemNode'?: (_zetasql_ResolvedReplaceFieldItemProto__Output | null);
  'resolvedConnectionNode'?: (_zetasql_ResolvedConnectionProto__Output | null);
  'resolvedExecuteImmediateArgumentNode'?: (_zetasql_ResolvedExecuteImmediateArgumentProto__Output | null);
  'resolvedDescriptorNode'?: (_zetasql_ResolvedDescriptorProto__Output | null);
  'resolvedExtendedCastElementNode'?: (_zetasql_ResolvedExtendedCastElementProto__Output | null);
  'resolvedWithPartitionColumnsNode'?: (_zetasql_ResolvedWithPartitionColumnsProto__Output | null);
  'resolvedExtendedCastNode'?: (_zetasql_ResolvedExtendedCastProto__Output | null);
  'resolvedInlineLambdaNode'?: (_zetasql_ResolvedInlineLambdaProto__Output | null);
  'resolvedConstraintNode'?: (_zetasql_AnyResolvedConstraintProto__Output | null);
  'resolvedPivotColumnNode'?: (_zetasql_ResolvedPivotColumnProto__Output | null);
  'resolvedReturningClauseNode'?: (_zetasql_ResolvedReturningClauseProto__Output | null);
  'resolvedUnpivotArgNode'?: (_zetasql_ResolvedUnpivotArgProto__Output | null);
  'resolvedFilterFieldArgNode'?: (_zetasql_ResolvedFilterFieldArgProto__Output | null);
  'resolvedTableAndColumnInfoNode'?: (_zetasql_ResolvedTableAndColumnInfoProto__Output | null);
  'resolvedColumnDefaultValueNode'?: (_zetasql_ResolvedColumnDefaultValueProto__Output | null);
  'resolvedObjectUnitNode'?: (_zetasql_ResolvedObjectUnitProto__Output | null);
  'resolvedAuxLoadDataPartitionFilterNode'?: (_zetasql_ResolvedAuxLoadDataPartitionFilterProto__Output | null);
  'resolvedCreateModelAliasedQueryNode'?: (_zetasql_ResolvedCreateModelAliasedQueryProto__Output | null);
  'node': "resolvedMakeProtoFieldNode"|"resolvedColumnHolderNode"|"resolvedComputedColumnNode"|"resolvedOrderByItemNode"|"resolvedOutputColumnNode"|"resolvedWithEntryNode"|"resolvedOptionNode"|"resolvedWindowPartitioningNode"|"resolvedWindowOrderingNode"|"resolvedWindowFrameNode"|"resolvedAnalyticFunctionGroupNode"|"resolvedWindowFrameExprNode"|"resolvedDmlvalueNode"|"resolvedAssertRowsModifiedNode"|"resolvedInsertRowNode"|"resolvedUpdateItemNode"|"resolvedPrivilegeNode"|"resolvedArgumentDefNode"|"resolvedArgumentListNode"|"resolvedFunctionArgumentNode"|"resolvedFunctionSignatureHolderNode"|"resolvedAggregateHavingModifierNode"|"resolvedColumnDefinitionNode"|"resolvedGroupingSetNode"|"resolvedSetOperationItemNode"|"resolvedIndexItemNode"|"resolvedMergeWhenNode"|"resolvedUpdateArrayItemNode"|"resolvedColumnAnnotationsNode"|"resolvedGeneratedColumnInfoNode"|"resolvedModelNode"|"resolvedAlterActionNode"|"resolvedUnnestItemNode"|"resolvedReplaceFieldItemNode"|"resolvedConnectionNode"|"resolvedExecuteImmediateArgumentNode"|"resolvedDescriptorNode"|"resolvedExtendedCastElementNode"|"resolvedWithPartitionColumnsNode"|"resolvedExtendedCastNode"|"resolvedInlineLambdaNode"|"resolvedConstraintNode"|"resolvedPivotColumnNode"|"resolvedReturningClauseNode"|"resolvedUnpivotArgNode"|"resolvedFilterFieldArgNode"|"resolvedTableAndColumnInfoNode"|"resolvedColumnDefaultValueNode"|"resolvedObjectUnitNode"|"resolvedAuxLoadDataPartitionFilterNode"|"resolvedCreateModelAliasedQueryNode";
}
