// Original file: src/protos/zetasql/parser/parse_tree.proto

import type { AnyASTStatementProto as _zetasql_AnyASTStatementProto, AnyASTStatementProto__Output as _zetasql_AnyASTStatementProto__Output } from '../zetasql/AnyASTStatementProto';
import type { AnyASTQueryExpressionProto as _zetasql_AnyASTQueryExpressionProto, AnyASTQueryExpressionProto__Output as _zetasql_AnyASTQueryExpressionProto__Output } from '../zetasql/AnyASTQueryExpressionProto';
import type { ASTSelectListProto as _zetasql_ASTSelectListProto, ASTSelectListProto__Output as _zetasql_ASTSelectListProto__Output } from '../zetasql/ASTSelectListProto';
import type { ASTSelectColumnProto as _zetasql_ASTSelectColumnProto, ASTSelectColumnProto__Output as _zetasql_ASTSelectColumnProto__Output } from '../zetasql/ASTSelectColumnProto';
import type { AnyASTExpressionProto as _zetasql_AnyASTExpressionProto, AnyASTExpressionProto__Output as _zetasql_AnyASTExpressionProto__Output } from '../zetasql/AnyASTExpressionProto';
import type { ASTAliasProto as _zetasql_ASTAliasProto, ASTAliasProto__Output as _zetasql_ASTAliasProto__Output } from '../zetasql/ASTAliasProto';
import type { AnyASTTableExpressionProto as _zetasql_AnyASTTableExpressionProto, AnyASTTableExpressionProto__Output as _zetasql_AnyASTTableExpressionProto__Output } from '../zetasql/AnyASTTableExpressionProto';
import type { ASTFromClauseProto as _zetasql_ASTFromClauseProto, ASTFromClauseProto__Output as _zetasql_ASTFromClauseProto__Output } from '../zetasql/ASTFromClauseProto';
import type { ASTWhereClauseProto as _zetasql_ASTWhereClauseProto, ASTWhereClauseProto__Output as _zetasql_ASTWhereClauseProto__Output } from '../zetasql/ASTWhereClauseProto';
import type { ASTGroupingItemProto as _zetasql_ASTGroupingItemProto, ASTGroupingItemProto__Output as _zetasql_ASTGroupingItemProto__Output } from '../zetasql/ASTGroupingItemProto';
import type { ASTGroupByProto as _zetasql_ASTGroupByProto, ASTGroupByProto__Output as _zetasql_ASTGroupByProto__Output } from '../zetasql/ASTGroupByProto';
import type { ASTOrderingExpressionProto as _zetasql_ASTOrderingExpressionProto, ASTOrderingExpressionProto__Output as _zetasql_ASTOrderingExpressionProto__Output } from '../zetasql/ASTOrderingExpressionProto';
import type { ASTOrderByProto as _zetasql_ASTOrderByProto, ASTOrderByProto__Output as _zetasql_ASTOrderByProto__Output } from '../zetasql/ASTOrderByProto';
import type { ASTLimitOffsetProto as _zetasql_ASTLimitOffsetProto, ASTLimitOffsetProto__Output as _zetasql_ASTLimitOffsetProto__Output } from '../zetasql/ASTLimitOffsetProto';
import type { ASTOnClauseProto as _zetasql_ASTOnClauseProto, ASTOnClauseProto__Output as _zetasql_ASTOnClauseProto__Output } from '../zetasql/ASTOnClauseProto';
import type { ASTWithClauseEntryProto as _zetasql_ASTWithClauseEntryProto, ASTWithClauseEntryProto__Output as _zetasql_ASTWithClauseEntryProto__Output } from '../zetasql/ASTWithClauseEntryProto';
import type { ASTWithClauseProto as _zetasql_ASTWithClauseProto, ASTWithClauseProto__Output as _zetasql_ASTWithClauseProto__Output } from '../zetasql/ASTWithClauseProto';
import type { ASTHavingProto as _zetasql_ASTHavingProto, ASTHavingProto__Output as _zetasql_ASTHavingProto__Output } from '../zetasql/ASTHavingProto';
import type { AnyASTTypeProto as _zetasql_AnyASTTypeProto, AnyASTTypeProto__Output as _zetasql_AnyASTTypeProto__Output } from '../zetasql/AnyASTTypeProto';
import type { ASTStructFieldProto as _zetasql_ASTStructFieldProto, ASTStructFieldProto__Output as _zetasql_ASTStructFieldProto__Output } from '../zetasql/ASTStructFieldProto';
import type { ASTSelectAsProto as _zetasql_ASTSelectAsProto, ASTSelectAsProto__Output as _zetasql_ASTSelectAsProto__Output } from '../zetasql/ASTSelectAsProto';
import type { ASTRollupProto as _zetasql_ASTRollupProto, ASTRollupProto__Output as _zetasql_ASTRollupProto__Output } from '../zetasql/ASTRollupProto';
import type { ASTStructConstructorArgProto as _zetasql_ASTStructConstructorArgProto, ASTStructConstructorArgProto__Output as _zetasql_ASTStructConstructorArgProto__Output } from '../zetasql/ASTStructConstructorArgProto';
import type { ASTInListProto as _zetasql_ASTInListProto, ASTInListProto__Output as _zetasql_ASTInListProto__Output } from '../zetasql/ASTInListProto';
import type { ASTCollateProto as _zetasql_ASTCollateProto, ASTCollateProto__Output as _zetasql_ASTCollateProto__Output } from '../zetasql/ASTCollateProto';
import type { ASTHavingModifierProto as _zetasql_ASTHavingModifierProto, ASTHavingModifierProto__Output as _zetasql_ASTHavingModifierProto__Output } from '../zetasql/ASTHavingModifierProto';
import type { ASTNullOrderProto as _zetasql_ASTNullOrderProto, ASTNullOrderProto__Output as _zetasql_ASTNullOrderProto__Output } from '../zetasql/ASTNullOrderProto';
import type { ASTOnOrUsingClauseListProto as _zetasql_ASTOnOrUsingClauseListProto, ASTOnOrUsingClauseListProto__Output as _zetasql_ASTOnOrUsingClauseListProto__Output } from '../zetasql/ASTOnOrUsingClauseListProto';
import type { ASTPartitionByProto as _zetasql_ASTPartitionByProto, ASTPartitionByProto__Output as _zetasql_ASTPartitionByProto__Output } from '../zetasql/ASTPartitionByProto';
import type { ASTStarExceptListProto as _zetasql_ASTStarExceptListProto, ASTStarExceptListProto__Output as _zetasql_ASTStarExceptListProto__Output } from '../zetasql/ASTStarExceptListProto';
import type { ASTStarModifiersProto as _zetasql_ASTStarModifiersProto, ASTStarModifiersProto__Output as _zetasql_ASTStarModifiersProto__Output } from '../zetasql/ASTStarModifiersProto';
import type { ASTStarReplaceItemProto as _zetasql_ASTStarReplaceItemProto, ASTStarReplaceItemProto__Output as _zetasql_ASTStarReplaceItemProto__Output } from '../zetasql/ASTStarReplaceItemProto';
import type { ASTUnnestExpressionProto as _zetasql_ASTUnnestExpressionProto, ASTUnnestExpressionProto__Output as _zetasql_ASTUnnestExpressionProto__Output } from '../zetasql/ASTUnnestExpressionProto';
import type { ASTWindowClauseProto as _zetasql_ASTWindowClauseProto, ASTWindowClauseProto__Output as _zetasql_ASTWindowClauseProto__Output } from '../zetasql/ASTWindowClauseProto';
import type { ASTWindowDefinitionProto as _zetasql_ASTWindowDefinitionProto, ASTWindowDefinitionProto__Output as _zetasql_ASTWindowDefinitionProto__Output } from '../zetasql/ASTWindowDefinitionProto';
import type { ASTWindowFrameProto as _zetasql_ASTWindowFrameProto, ASTWindowFrameProto__Output as _zetasql_ASTWindowFrameProto__Output } from '../zetasql/ASTWindowFrameProto';
import type { ASTWindowFrameExprProto as _zetasql_ASTWindowFrameExprProto, ASTWindowFrameExprProto__Output as _zetasql_ASTWindowFrameExprProto__Output } from '../zetasql/ASTWindowFrameExprProto';
import type { ASTWindowSpecificationProto as _zetasql_ASTWindowSpecificationProto, ASTWindowSpecificationProto__Output as _zetasql_ASTWindowSpecificationProto__Output } from '../zetasql/ASTWindowSpecificationProto';
import type { ASTWithOffsetProto as _zetasql_ASTWithOffsetProto, ASTWithOffsetProto__Output as _zetasql_ASTWithOffsetProto__Output } from '../zetasql/ASTWithOffsetProto';
import type { ASTAnySomeAllOpProto as _zetasql_ASTAnySomeAllOpProto, ASTAnySomeAllOpProto__Output as _zetasql_ASTAnySomeAllOpProto__Output } from '../zetasql/ASTAnySomeAllOpProto';
import type { ASTStatementListProto as _zetasql_ASTStatementListProto, ASTStatementListProto__Output as _zetasql_ASTStatementListProto__Output } from '../zetasql/ASTStatementListProto';
import type { AnyASTTransactionModeProto as _zetasql_AnyASTTransactionModeProto, AnyASTTransactionModeProto__Output as _zetasql_AnyASTTransactionModeProto__Output } from '../zetasql/AnyASTTransactionModeProto';
import type { ASTTransactionModeListProto as _zetasql_ASTTransactionModeListProto, ASTTransactionModeListProto__Output as _zetasql_ASTTransactionModeListProto__Output } from '../zetasql/ASTTransactionModeListProto';
import type { ASTWithConnectionClauseProto as _zetasql_ASTWithConnectionClauseProto, ASTWithConnectionClauseProto__Output as _zetasql_ASTWithConnectionClauseProto__Output } from '../zetasql/ASTWithConnectionClauseProto';
import type { ASTIntoAliasProto as _zetasql_ASTIntoAliasProto, ASTIntoAliasProto__Output as _zetasql_ASTIntoAliasProto__Output } from '../zetasql/ASTIntoAliasProto';
import type { ASTUnnestExpressionWithOptAliasAndOffsetProto as _zetasql_ASTUnnestExpressionWithOptAliasAndOffsetProto, ASTUnnestExpressionWithOptAliasAndOffsetProto__Output as _zetasql_ASTUnnestExpressionWithOptAliasAndOffsetProto__Output } from '../zetasql/ASTUnnestExpressionWithOptAliasAndOffsetProto';
import type { ASTPivotExpressionProto as _zetasql_ASTPivotExpressionProto, ASTPivotExpressionProto__Output as _zetasql_ASTPivotExpressionProto__Output } from '../zetasql/ASTPivotExpressionProto';
import type { ASTPivotValueProto as _zetasql_ASTPivotValueProto, ASTPivotValueProto__Output as _zetasql_ASTPivotValueProto__Output } from '../zetasql/ASTPivotValueProto';
import type { ASTPivotExpressionListProto as _zetasql_ASTPivotExpressionListProto, ASTPivotExpressionListProto__Output as _zetasql_ASTPivotExpressionListProto__Output } from '../zetasql/ASTPivotExpressionListProto';
import type { ASTPivotValueListProto as _zetasql_ASTPivotValueListProto, ASTPivotValueListProto__Output as _zetasql_ASTPivotValueListProto__Output } from '../zetasql/ASTPivotValueListProto';
import type { ASTPivotClauseProto as _zetasql_ASTPivotClauseProto, ASTPivotClauseProto__Output as _zetasql_ASTPivotClauseProto__Output } from '../zetasql/ASTPivotClauseProto';
import type { ASTUnpivotInItemProto as _zetasql_ASTUnpivotInItemProto, ASTUnpivotInItemProto__Output as _zetasql_ASTUnpivotInItemProto__Output } from '../zetasql/ASTUnpivotInItemProto';
import type { ASTUnpivotInItemListProto as _zetasql_ASTUnpivotInItemListProto, ASTUnpivotInItemListProto__Output as _zetasql_ASTUnpivotInItemListProto__Output } from '../zetasql/ASTUnpivotInItemListProto';
import type { ASTUnpivotClauseProto as _zetasql_ASTUnpivotClauseProto, ASTUnpivotClauseProto__Output as _zetasql_ASTUnpivotClauseProto__Output } from '../zetasql/ASTUnpivotClauseProto';
import type { ASTUsingClauseProto as _zetasql_ASTUsingClauseProto, ASTUsingClauseProto__Output as _zetasql_ASTUsingClauseProto__Output } from '../zetasql/ASTUsingClauseProto';
import type { ASTForSystemTimeProto as _zetasql_ASTForSystemTimeProto, ASTForSystemTimeProto__Output as _zetasql_ASTForSystemTimeProto__Output } from '../zetasql/ASTForSystemTimeProto';
import type { ASTQualifyProto as _zetasql_ASTQualifyProto, ASTQualifyProto__Output as _zetasql_ASTQualifyProto__Output } from '../zetasql/ASTQualifyProto';
import type { ASTClampedBetweenModifierProto as _zetasql_ASTClampedBetweenModifierProto, ASTClampedBetweenModifierProto__Output as _zetasql_ASTClampedBetweenModifierProto__Output } from '../zetasql/ASTClampedBetweenModifierProto';
import type { ASTFormatClauseProto as _zetasql_ASTFormatClauseProto, ASTFormatClauseProto__Output as _zetasql_ASTFormatClauseProto__Output } from '../zetasql/ASTFormatClauseProto';
import type { ASTPathExpressionListProto as _zetasql_ASTPathExpressionListProto, ASTPathExpressionListProto__Output as _zetasql_ASTPathExpressionListProto__Output } from '../zetasql/ASTPathExpressionListProto';
import type { ASTWithGroupRowsProto as _zetasql_ASTWithGroupRowsProto, ASTWithGroupRowsProto__Output as _zetasql_ASTWithGroupRowsProto__Output } from '../zetasql/ASTWithGroupRowsProto';
import type { ASTClusterByProto as _zetasql_ASTClusterByProto, ASTClusterByProto__Output as _zetasql_ASTClusterByProto__Output } from '../zetasql/ASTClusterByProto';
import type { ASTNewConstructorArgProto as _zetasql_ASTNewConstructorArgProto, ASTNewConstructorArgProto__Output as _zetasql_ASTNewConstructorArgProto__Output } from '../zetasql/ASTNewConstructorArgProto';
import type { ASTOptionsListProto as _zetasql_ASTOptionsListProto, ASTOptionsListProto__Output as _zetasql_ASTOptionsListProto__Output } from '../zetasql/ASTOptionsListProto';
import type { ASTOptionsEntryProto as _zetasql_ASTOptionsEntryProto, ASTOptionsEntryProto__Output as _zetasql_ASTOptionsEntryProto__Output } from '../zetasql/ASTOptionsEntryProto';
import type { ASTFunctionParameterProto as _zetasql_ASTFunctionParameterProto, ASTFunctionParameterProto__Output as _zetasql_ASTFunctionParameterProto__Output } from '../zetasql/ASTFunctionParameterProto';
import type { ASTFunctionParametersProto as _zetasql_ASTFunctionParametersProto, ASTFunctionParametersProto__Output as _zetasql_ASTFunctionParametersProto__Output } from '../zetasql/ASTFunctionParametersProto';
import type { ASTFunctionDeclarationProto as _zetasql_ASTFunctionDeclarationProto, ASTFunctionDeclarationProto__Output as _zetasql_ASTFunctionDeclarationProto__Output } from '../zetasql/ASTFunctionDeclarationProto';
import type { ASTSqlFunctionBodyProto as _zetasql_ASTSqlFunctionBodyProto, ASTSqlFunctionBodyProto__Output as _zetasql_ASTSqlFunctionBodyProto__Output } from '../zetasql/ASTSqlFunctionBodyProto';
import type { ASTTVFArgumentProto as _zetasql_ASTTVFArgumentProto, ASTTVFArgumentProto__Output as _zetasql_ASTTVFArgumentProto__Output } from '../zetasql/ASTTVFArgumentProto';
import type { ASTTableClauseProto as _zetasql_ASTTableClauseProto, ASTTableClauseProto__Output as _zetasql_ASTTableClauseProto__Output } from '../zetasql/ASTTableClauseProto';
import type { ASTModelClauseProto as _zetasql_ASTModelClauseProto, ASTModelClauseProto__Output as _zetasql_ASTModelClauseProto__Output } from '../zetasql/ASTModelClauseProto';
import type { ASTConnectionClauseProto as _zetasql_ASTConnectionClauseProto, ASTConnectionClauseProto__Output as _zetasql_ASTConnectionClauseProto__Output } from '../zetasql/ASTConnectionClauseProto';
import type { ASTCloneDataSourceListProto as _zetasql_ASTCloneDataSourceListProto, ASTCloneDataSourceListProto__Output as _zetasql_ASTCloneDataSourceListProto__Output } from '../zetasql/ASTCloneDataSourceListProto';
import type { ASTTransformClauseProto as _zetasql_ASTTransformClauseProto, ASTTransformClauseProto__Output as _zetasql_ASTTransformClauseProto__Output } from '../zetasql/ASTTransformClauseProto';
import type { ASTIndexItemListProto as _zetasql_ASTIndexItemListProto, ASTIndexItemListProto__Output as _zetasql_ASTIndexItemListProto__Output } from '../zetasql/ASTIndexItemListProto';
import type { ASTIndexStoringExpressionListProto as _zetasql_ASTIndexStoringExpressionListProto, ASTIndexStoringExpressionListProto__Output as _zetasql_ASTIndexStoringExpressionListProto__Output } from '../zetasql/ASTIndexStoringExpressionListProto';
import type { ASTIndexUnnestExpressionListProto as _zetasql_ASTIndexUnnestExpressionListProto, ASTIndexUnnestExpressionListProto__Output as _zetasql_ASTIndexUnnestExpressionListProto__Output } from '../zetasql/ASTIndexUnnestExpressionListProto';
import type { ASTWithPartitionColumnsClauseProto as _zetasql_ASTWithPartitionColumnsClauseProto, ASTWithPartitionColumnsClauseProto__Output as _zetasql_ASTWithPartitionColumnsClauseProto__Output } from '../zetasql/ASTWithPartitionColumnsClauseProto';
import type { ASTTypeParameterListProto as _zetasql_ASTTypeParameterListProto, ASTTypeParameterListProto__Output as _zetasql_ASTTypeParameterListProto__Output } from '../zetasql/ASTTypeParameterListProto';
import type { ASTTVFSchemaProto as _zetasql_ASTTVFSchemaProto, ASTTVFSchemaProto__Output as _zetasql_ASTTVFSchemaProto__Output } from '../zetasql/ASTTVFSchemaProto';
import type { ASTTVFSchemaColumnProto as _zetasql_ASTTVFSchemaColumnProto, ASTTVFSchemaColumnProto__Output as _zetasql_ASTTVFSchemaColumnProto__Output } from '../zetasql/ASTTVFSchemaColumnProto';
import type { ASTTableAndColumnInfoProto as _zetasql_ASTTableAndColumnInfoProto, ASTTableAndColumnInfoProto__Output as _zetasql_ASTTableAndColumnInfoProto__Output } from '../zetasql/ASTTableAndColumnInfoProto';
import type { ASTTableAndColumnInfoListProto as _zetasql_ASTTableAndColumnInfoListProto, ASTTableAndColumnInfoListProto__Output as _zetasql_ASTTableAndColumnInfoListProto__Output } from '../zetasql/ASTTableAndColumnInfoListProto';
import type { ASTTemplatedParameterTypeProto as _zetasql_ASTTemplatedParameterTypeProto, ASTTemplatedParameterTypeProto__Output as _zetasql_ASTTemplatedParameterTypeProto__Output } from '../zetasql/ASTTemplatedParameterTypeProto';
import type { ASTAssertRowsModifiedProto as _zetasql_ASTAssertRowsModifiedProto, ASTAssertRowsModifiedProto__Output as _zetasql_ASTAssertRowsModifiedProto__Output } from '../zetasql/ASTAssertRowsModifiedProto';
import type { ASTReturningClauseProto as _zetasql_ASTReturningClauseProto, ASTReturningClauseProto__Output as _zetasql_ASTReturningClauseProto__Output } from '../zetasql/ASTReturningClauseProto';
import type { AnyASTColumnAttributeProto as _zetasql_AnyASTColumnAttributeProto, AnyASTColumnAttributeProto__Output as _zetasql_AnyASTColumnAttributeProto__Output } from '../zetasql/AnyASTColumnAttributeProto';
import type { ASTColumnAttributeListProto as _zetasql_ASTColumnAttributeListProto, ASTColumnAttributeListProto__Output as _zetasql_ASTColumnAttributeListProto__Output } from '../zetasql/ASTColumnAttributeListProto';
import type { ASTStructColumnFieldProto as _zetasql_ASTStructColumnFieldProto, ASTStructColumnFieldProto__Output as _zetasql_ASTStructColumnFieldProto__Output } from '../zetasql/ASTStructColumnFieldProto';
import type { ASTGeneratedColumnInfoProto as _zetasql_ASTGeneratedColumnInfoProto, ASTGeneratedColumnInfoProto__Output as _zetasql_ASTGeneratedColumnInfoProto__Output } from '../zetasql/ASTGeneratedColumnInfoProto';
import type { AnyASTTableElementProto as _zetasql_AnyASTTableElementProto, AnyASTTableElementProto__Output as _zetasql_AnyASTTableElementProto__Output } from '../zetasql/AnyASTTableElementProto';
import type { ASTTableElementListProto as _zetasql_ASTTableElementListProto, ASTTableElementListProto__Output as _zetasql_ASTTableElementListProto__Output } from '../zetasql/ASTTableElementListProto';
import type { ASTColumnListProto as _zetasql_ASTColumnListProto, ASTColumnListProto__Output as _zetasql_ASTColumnListProto__Output } from '../zetasql/ASTColumnListProto';
import type { ASTColumnPositionProto as _zetasql_ASTColumnPositionProto, ASTColumnPositionProto__Output as _zetasql_ASTColumnPositionProto__Output } from '../zetasql/ASTColumnPositionProto';
import type { ASTInsertValuesRowProto as _zetasql_ASTInsertValuesRowProto, ASTInsertValuesRowProto__Output as _zetasql_ASTInsertValuesRowProto__Output } from '../zetasql/ASTInsertValuesRowProto';
import type { ASTInsertValuesRowListProto as _zetasql_ASTInsertValuesRowListProto, ASTInsertValuesRowListProto__Output as _zetasql_ASTInsertValuesRowListProto__Output } from '../zetasql/ASTInsertValuesRowListProto';
import type { ASTUpdateSetValueProto as _zetasql_ASTUpdateSetValueProto, ASTUpdateSetValueProto__Output as _zetasql_ASTUpdateSetValueProto__Output } from '../zetasql/ASTUpdateSetValueProto';
import type { ASTUpdateItemProto as _zetasql_ASTUpdateItemProto, ASTUpdateItemProto__Output as _zetasql_ASTUpdateItemProto__Output } from '../zetasql/ASTUpdateItemProto';
import type { ASTUpdateItemListProto as _zetasql_ASTUpdateItemListProto, ASTUpdateItemListProto__Output as _zetasql_ASTUpdateItemListProto__Output } from '../zetasql/ASTUpdateItemListProto';
import type { ASTMergeActionProto as _zetasql_ASTMergeActionProto, ASTMergeActionProto__Output as _zetasql_ASTMergeActionProto__Output } from '../zetasql/ASTMergeActionProto';
import type { ASTMergeWhenClauseProto as _zetasql_ASTMergeWhenClauseProto, ASTMergeWhenClauseProto__Output as _zetasql_ASTMergeWhenClauseProto__Output } from '../zetasql/ASTMergeWhenClauseProto';
import type { ASTMergeWhenClauseListProto as _zetasql_ASTMergeWhenClauseListProto, ASTMergeWhenClauseListProto__Output as _zetasql_ASTMergeWhenClauseListProto__Output } from '../zetasql/ASTMergeWhenClauseListProto';
import type { ASTPrivilegeProto as _zetasql_ASTPrivilegeProto, ASTPrivilegeProto__Output as _zetasql_ASTPrivilegeProto__Output } from '../zetasql/ASTPrivilegeProto';
import type { ASTPrivilegesProto as _zetasql_ASTPrivilegesProto, ASTPrivilegesProto__Output as _zetasql_ASTPrivilegesProto__Output } from '../zetasql/ASTPrivilegesProto';
import type { ASTGranteeListProto as _zetasql_ASTGranteeListProto, ASTGranteeListProto__Output as _zetasql_ASTGranteeListProto__Output } from '../zetasql/ASTGranteeListProto';
import type { ASTRepeatableClauseProto as _zetasql_ASTRepeatableClauseProto, ASTRepeatableClauseProto__Output as _zetasql_ASTRepeatableClauseProto__Output } from '../zetasql/ASTRepeatableClauseProto';
import type { ASTFilterFieldsArgProto as _zetasql_ASTFilterFieldsArgProto, ASTFilterFieldsArgProto__Output as _zetasql_ASTFilterFieldsArgProto__Output } from '../zetasql/ASTFilterFieldsArgProto';
import type { ASTReplaceFieldsArgProto as _zetasql_ASTReplaceFieldsArgProto, ASTReplaceFieldsArgProto__Output as _zetasql_ASTReplaceFieldsArgProto__Output } from '../zetasql/ASTReplaceFieldsArgProto';
import type { ASTSampleSizeProto as _zetasql_ASTSampleSizeProto, ASTSampleSizeProto__Output as _zetasql_ASTSampleSizeProto__Output } from '../zetasql/ASTSampleSizeProto';
import type { ASTWithWeightProto as _zetasql_ASTWithWeightProto, ASTWithWeightProto__Output as _zetasql_ASTWithWeightProto__Output } from '../zetasql/ASTWithWeightProto';
import type { ASTSampleSuffixProto as _zetasql_ASTSampleSuffixProto, ASTSampleSuffixProto__Output as _zetasql_ASTSampleSuffixProto__Output } from '../zetasql/ASTSampleSuffixProto';
import type { ASTSampleClauseProto as _zetasql_ASTSampleClauseProto, ASTSampleClauseProto__Output as _zetasql_ASTSampleClauseProto__Output } from '../zetasql/ASTSampleClauseProto';
import type { AnyASTAlterActionProto as _zetasql_AnyASTAlterActionProto, AnyASTAlterActionProto__Output as _zetasql_AnyASTAlterActionProto__Output } from '../zetasql/AnyASTAlterActionProto';
import type { ASTAlterActionListProto as _zetasql_ASTAlterActionListProto, ASTAlterActionListProto__Output as _zetasql_ASTAlterActionListProto__Output } from '../zetasql/ASTAlterActionListProto';
import type { ASTForeignKeyActionsProto as _zetasql_ASTForeignKeyActionsProto, ASTForeignKeyActionsProto__Output as _zetasql_ASTForeignKeyActionsProto__Output } from '../zetasql/ASTForeignKeyActionsProto';
import type { ASTForeignKeyReferenceProto as _zetasql_ASTForeignKeyReferenceProto, ASTForeignKeyReferenceProto__Output as _zetasql_ASTForeignKeyReferenceProto__Output } from '../zetasql/ASTForeignKeyReferenceProto';
import type { ASTScriptProto as _zetasql_ASTScriptProto, ASTScriptProto__Output as _zetasql_ASTScriptProto__Output } from '../zetasql/ASTScriptProto';
import type { ASTElseifClauseProto as _zetasql_ASTElseifClauseProto, ASTElseifClauseProto__Output as _zetasql_ASTElseifClauseProto__Output } from '../zetasql/ASTElseifClauseProto';
import type { ASTElseifClauseListProto as _zetasql_ASTElseifClauseListProto, ASTElseifClauseListProto__Output as _zetasql_ASTElseifClauseListProto__Output } from '../zetasql/ASTElseifClauseListProto';
import type { ASTWhenThenClauseProto as _zetasql_ASTWhenThenClauseProto, ASTWhenThenClauseProto__Output as _zetasql_ASTWhenThenClauseProto__Output } from '../zetasql/ASTWhenThenClauseProto';
import type { ASTWhenThenClauseListProto as _zetasql_ASTWhenThenClauseListProto, ASTWhenThenClauseListProto__Output as _zetasql_ASTWhenThenClauseListProto__Output } from '../zetasql/ASTWhenThenClauseListProto';
import type { ASTHintProto as _zetasql_ASTHintProto, ASTHintProto__Output as _zetasql_ASTHintProto__Output } from '../zetasql/ASTHintProto';
import type { ASTHintEntryProto as _zetasql_ASTHintEntryProto, ASTHintEntryProto__Output as _zetasql_ASTHintEntryProto__Output } from '../zetasql/ASTHintEntryProto';
import type { ASTUnpivotInItemLabelProto as _zetasql_ASTUnpivotInItemLabelProto, ASTUnpivotInItemLabelProto__Output as _zetasql_ASTUnpivotInItemLabelProto__Output } from '../zetasql/ASTUnpivotInItemLabelProto';
import type { ASTDescriptorProto as _zetasql_ASTDescriptorProto, ASTDescriptorProto__Output as _zetasql_ASTDescriptorProto__Output } from '../zetasql/ASTDescriptorProto';
import type { AnyASTColumnSchemaProto as _zetasql_AnyASTColumnSchemaProto, AnyASTColumnSchemaProto__Output as _zetasql_AnyASTColumnSchemaProto__Output } from '../zetasql/AnyASTColumnSchemaProto';
import type { ASTDescriptorColumnProto as _zetasql_ASTDescriptorColumnProto, ASTDescriptorColumnProto__Output as _zetasql_ASTDescriptorColumnProto__Output } from '../zetasql/ASTDescriptorColumnProto';
import type { ASTDescriptorColumnListProto as _zetasql_ASTDescriptorColumnListProto, ASTDescriptorColumnListProto__Output as _zetasql_ASTDescriptorColumnListProto__Output } from '../zetasql/ASTDescriptorColumnListProto';
import type { ASTExceptionHandlerProto as _zetasql_ASTExceptionHandlerProto, ASTExceptionHandlerProto__Output as _zetasql_ASTExceptionHandlerProto__Output } from '../zetasql/ASTExceptionHandlerProto';
import type { ASTExceptionHandlerListProto as _zetasql_ASTExceptionHandlerListProto, ASTExceptionHandlerListProto__Output as _zetasql_ASTExceptionHandlerListProto__Output } from '../zetasql/ASTExceptionHandlerListProto';
import type { ASTIdentifierListProto as _zetasql_ASTIdentifierListProto, ASTIdentifierListProto__Output as _zetasql_ASTIdentifierListProto__Output } from '../zetasql/ASTIdentifierListProto';
import type { ASTUntilClauseProto as _zetasql_ASTUntilClauseProto, ASTUntilClauseProto__Output as _zetasql_ASTUntilClauseProto__Output } from '../zetasql/ASTUntilClauseProto';
import type { ASTExecuteIntoClauseProto as _zetasql_ASTExecuteIntoClauseProto, ASTExecuteIntoClauseProto__Output as _zetasql_ASTExecuteIntoClauseProto__Output } from '../zetasql/ASTExecuteIntoClauseProto';
import type { ASTExecuteUsingArgumentProto as _zetasql_ASTExecuteUsingArgumentProto, ASTExecuteUsingArgumentProto__Output as _zetasql_ASTExecuteUsingArgumentProto__Output } from '../zetasql/ASTExecuteUsingArgumentProto';
import type { ASTExecuteUsingClauseProto as _zetasql_ASTExecuteUsingClauseProto, ASTExecuteUsingClauseProto__Output as _zetasql_ASTExecuteUsingClauseProto__Output } from '../zetasql/ASTExecuteUsingClauseProto';
import type { ASTAuxLoadDataFromFilesOptionsListProto as _zetasql_ASTAuxLoadDataFromFilesOptionsListProto, ASTAuxLoadDataFromFilesOptionsListProto__Output as _zetasql_ASTAuxLoadDataFromFilesOptionsListProto__Output } from '../zetasql/ASTAuxLoadDataFromFilesOptionsListProto';
import type { ASTLabelProto as _zetasql_ASTLabelProto, ASTLabelProto__Output as _zetasql_ASTLabelProto__Output } from '../zetasql/ASTLabelProto';
import type { ASTBracedConstructorFieldProto as _zetasql_ASTBracedConstructorFieldProto, ASTBracedConstructorFieldProto__Output as _zetasql_ASTBracedConstructorFieldProto__Output } from '../zetasql/ASTBracedConstructorFieldProto';

export interface AnyASTNodeProto {
  'astStatementNode'?: (_zetasql_AnyASTStatementProto | null);
  'astQueryExpressionNode'?: (_zetasql_AnyASTQueryExpressionProto | null);
  'astSelectListNode'?: (_zetasql_ASTSelectListProto | null);
  'astSelectColumnNode'?: (_zetasql_ASTSelectColumnProto | null);
  'astExpressionNode'?: (_zetasql_AnyASTExpressionProto | null);
  'astAliasNode'?: (_zetasql_ASTAliasProto | null);
  'astTableExpressionNode'?: (_zetasql_AnyASTTableExpressionProto | null);
  'astFromClauseNode'?: (_zetasql_ASTFromClauseProto | null);
  'astWhereClauseNode'?: (_zetasql_ASTWhereClauseProto | null);
  'astGroupingItemNode'?: (_zetasql_ASTGroupingItemProto | null);
  'astGroupByNode'?: (_zetasql_ASTGroupByProto | null);
  'astOrderingExpressionNode'?: (_zetasql_ASTOrderingExpressionProto | null);
  'astOrderByNode'?: (_zetasql_ASTOrderByProto | null);
  'astLimitOffsetNode'?: (_zetasql_ASTLimitOffsetProto | null);
  'astOnClauseNode'?: (_zetasql_ASTOnClauseProto | null);
  'astWithClauseEntryNode'?: (_zetasql_ASTWithClauseEntryProto | null);
  'astWithClauseNode'?: (_zetasql_ASTWithClauseProto | null);
  'astHavingNode'?: (_zetasql_ASTHavingProto | null);
  'astTypeNode'?: (_zetasql_AnyASTTypeProto | null);
  'astStructFieldNode'?: (_zetasql_ASTStructFieldProto | null);
  'astSelectAsNode'?: (_zetasql_ASTSelectAsProto | null);
  'astRollupNode'?: (_zetasql_ASTRollupProto | null);
  'astStructConstructorArgNode'?: (_zetasql_ASTStructConstructorArgProto | null);
  'astInListNode'?: (_zetasql_ASTInListProto | null);
  'astCollateNode'?: (_zetasql_ASTCollateProto | null);
  'astHavingModifierNode'?: (_zetasql_ASTHavingModifierProto | null);
  'astNullOrderNode'?: (_zetasql_ASTNullOrderProto | null);
  'astOnOrUsingClauseListNode'?: (_zetasql_ASTOnOrUsingClauseListProto | null);
  'astPartitionByNode'?: (_zetasql_ASTPartitionByProto | null);
  'astStarExceptListNode'?: (_zetasql_ASTStarExceptListProto | null);
  'astStarModifiersNode'?: (_zetasql_ASTStarModifiersProto | null);
  'astStarReplaceItemNode'?: (_zetasql_ASTStarReplaceItemProto | null);
  'astUnnestExpressionNode'?: (_zetasql_ASTUnnestExpressionProto | null);
  'astWindowClauseNode'?: (_zetasql_ASTWindowClauseProto | null);
  'astWindowDefinitionNode'?: (_zetasql_ASTWindowDefinitionProto | null);
  'astWindowFrameNode'?: (_zetasql_ASTWindowFrameProto | null);
  'astWindowFrameExprNode'?: (_zetasql_ASTWindowFrameExprProto | null);
  'astWindowSpecificationNode'?: (_zetasql_ASTWindowSpecificationProto | null);
  'astWithOffsetNode'?: (_zetasql_ASTWithOffsetProto | null);
  'astAnySomeAllOpNode'?: (_zetasql_ASTAnySomeAllOpProto | null);
  'astStatementListNode'?: (_zetasql_ASTStatementListProto | null);
  'astTransactionModeNode'?: (_zetasql_AnyASTTransactionModeProto | null);
  'astTransactionModeListNode'?: (_zetasql_ASTTransactionModeListProto | null);
  'astWithConnectionClauseNode'?: (_zetasql_ASTWithConnectionClauseProto | null);
  'astIntoAliasNode'?: (_zetasql_ASTIntoAliasProto | null);
  'astUnnestExpressionWithOptAliasAndOffsetNode'?: (_zetasql_ASTUnnestExpressionWithOptAliasAndOffsetProto | null);
  'astPivotExpressionNode'?: (_zetasql_ASTPivotExpressionProto | null);
  'astPivotValueNode'?: (_zetasql_ASTPivotValueProto | null);
  'astPivotExpressionListNode'?: (_zetasql_ASTPivotExpressionListProto | null);
  'astPivotValueListNode'?: (_zetasql_ASTPivotValueListProto | null);
  'astPivotClauseNode'?: (_zetasql_ASTPivotClauseProto | null);
  'astUnpivotInItemNode'?: (_zetasql_ASTUnpivotInItemProto | null);
  'astUnpivotInItemListNode'?: (_zetasql_ASTUnpivotInItemListProto | null);
  'astUnpivotClauseNode'?: (_zetasql_ASTUnpivotClauseProto | null);
  'astUsingClauseNode'?: (_zetasql_ASTUsingClauseProto | null);
  'astForSystemTimeNode'?: (_zetasql_ASTForSystemTimeProto | null);
  'astQualifyNode'?: (_zetasql_ASTQualifyProto | null);
  'astClampedBetweenModifierNode'?: (_zetasql_ASTClampedBetweenModifierProto | null);
  'astFormatClauseNode'?: (_zetasql_ASTFormatClauseProto | null);
  'astPathExpressionListNode'?: (_zetasql_ASTPathExpressionListProto | null);
  'astWithGroupRowsNode'?: (_zetasql_ASTWithGroupRowsProto | null);
  'astClusterByNode'?: (_zetasql_ASTClusterByProto | null);
  'astNewConstructorArgNode'?: (_zetasql_ASTNewConstructorArgProto | null);
  'astOptionsListNode'?: (_zetasql_ASTOptionsListProto | null);
  'astOptionsEntryNode'?: (_zetasql_ASTOptionsEntryProto | null);
  'astFunctionParameterNode'?: (_zetasql_ASTFunctionParameterProto | null);
  'astFunctionParametersNode'?: (_zetasql_ASTFunctionParametersProto | null);
  'astFunctionDeclarationNode'?: (_zetasql_ASTFunctionDeclarationProto | null);
  'astSqlFunctionBodyNode'?: (_zetasql_ASTSqlFunctionBodyProto | null);
  'astTvfArgumentNode'?: (_zetasql_ASTTVFArgumentProto | null);
  'astTableClauseNode'?: (_zetasql_ASTTableClauseProto | null);
  'astModelClauseNode'?: (_zetasql_ASTModelClauseProto | null);
  'astConnectionClauseNode'?: (_zetasql_ASTConnectionClauseProto | null);
  'astCloneDataSourceListNode'?: (_zetasql_ASTCloneDataSourceListProto | null);
  'astTransformClauseNode'?: (_zetasql_ASTTransformClauseProto | null);
  'astIndexItemListNode'?: (_zetasql_ASTIndexItemListProto | null);
  'astIndexStoringExpressionListNode'?: (_zetasql_ASTIndexStoringExpressionListProto | null);
  'astIndexUnnestExpressionListNode'?: (_zetasql_ASTIndexUnnestExpressionListProto | null);
  'astWithPartitionColumnsClauseNode'?: (_zetasql_ASTWithPartitionColumnsClauseProto | null);
  'astTypeParameterListNode'?: (_zetasql_ASTTypeParameterListProto | null);
  'astTvfSchemaNode'?: (_zetasql_ASTTVFSchemaProto | null);
  'astTvfSchemaColumnNode'?: (_zetasql_ASTTVFSchemaColumnProto | null);
  'astTableAndColumnInfoNode'?: (_zetasql_ASTTableAndColumnInfoProto | null);
  'astTableAndColumnInfoListNode'?: (_zetasql_ASTTableAndColumnInfoListProto | null);
  'astTemplatedParameterTypeNode'?: (_zetasql_ASTTemplatedParameterTypeProto | null);
  'astAssertRowsModifiedNode'?: (_zetasql_ASTAssertRowsModifiedProto | null);
  'astReturningClauseNode'?: (_zetasql_ASTReturningClauseProto | null);
  'astColumnAttributeNode'?: (_zetasql_AnyASTColumnAttributeProto | null);
  'astColumnAttributeListNode'?: (_zetasql_ASTColumnAttributeListProto | null);
  'astStructColumnFieldNode'?: (_zetasql_ASTStructColumnFieldProto | null);
  'astGeneratedColumnInfoNode'?: (_zetasql_ASTGeneratedColumnInfoProto | null);
  'astTableElementNode'?: (_zetasql_AnyASTTableElementProto | null);
  'astTableElementListNode'?: (_zetasql_ASTTableElementListProto | null);
  'astColumnListNode'?: (_zetasql_ASTColumnListProto | null);
  'astColumnPositionNode'?: (_zetasql_ASTColumnPositionProto | null);
  'astInsertValuesRowNode'?: (_zetasql_ASTInsertValuesRowProto | null);
  'astInsertValuesRowListNode'?: (_zetasql_ASTInsertValuesRowListProto | null);
  'astUpdateSetValueNode'?: (_zetasql_ASTUpdateSetValueProto | null);
  'astUpdateItemNode'?: (_zetasql_ASTUpdateItemProto | null);
  'astUpdateItemListNode'?: (_zetasql_ASTUpdateItemListProto | null);
  'astMergeActionNode'?: (_zetasql_ASTMergeActionProto | null);
  'astMergeWhenClauseNode'?: (_zetasql_ASTMergeWhenClauseProto | null);
  'astMergeWhenClauseListNode'?: (_zetasql_ASTMergeWhenClauseListProto | null);
  'astPrivilegeNode'?: (_zetasql_ASTPrivilegeProto | null);
  'astPrivilegesNode'?: (_zetasql_ASTPrivilegesProto | null);
  'astGranteeListNode'?: (_zetasql_ASTGranteeListProto | null);
  'astRepeatableClauseNode'?: (_zetasql_ASTRepeatableClauseProto | null);
  'astFilterFieldsArgNode'?: (_zetasql_ASTFilterFieldsArgProto | null);
  'astReplaceFieldsArgNode'?: (_zetasql_ASTReplaceFieldsArgProto | null);
  'astSampleSizeNode'?: (_zetasql_ASTSampleSizeProto | null);
  'astWithWeightNode'?: (_zetasql_ASTWithWeightProto | null);
  'astSampleSuffixNode'?: (_zetasql_ASTSampleSuffixProto | null);
  'astSampleClauseNode'?: (_zetasql_ASTSampleClauseProto | null);
  'astAlterActionNode'?: (_zetasql_AnyASTAlterActionProto | null);
  'astAlterActionListNode'?: (_zetasql_ASTAlterActionListProto | null);
  'astForeignKeyActionsNode'?: (_zetasql_ASTForeignKeyActionsProto | null);
  'astForeignKeyReferenceNode'?: (_zetasql_ASTForeignKeyReferenceProto | null);
  'astScriptNode'?: (_zetasql_ASTScriptProto | null);
  'astElseifClauseNode'?: (_zetasql_ASTElseifClauseProto | null);
  'astElseifClauseListNode'?: (_zetasql_ASTElseifClauseListProto | null);
  'astWhenThenClauseNode'?: (_zetasql_ASTWhenThenClauseProto | null);
  'astWhenThenClauseListNode'?: (_zetasql_ASTWhenThenClauseListProto | null);
  'astHintNode'?: (_zetasql_ASTHintProto | null);
  'astHintEntryNode'?: (_zetasql_ASTHintEntryProto | null);
  'astUnpivotInItemLabelNode'?: (_zetasql_ASTUnpivotInItemLabelProto | null);
  'astDescriptorNode'?: (_zetasql_ASTDescriptorProto | null);
  'astColumnSchemaNode'?: (_zetasql_AnyASTColumnSchemaProto | null);
  'astDescriptorColumnNode'?: (_zetasql_ASTDescriptorColumnProto | null);
  'astDescriptorColumnListNode'?: (_zetasql_ASTDescriptorColumnListProto | null);
  'astExceptionHandlerNode'?: (_zetasql_ASTExceptionHandlerProto | null);
  'astExceptionHandlerListNode'?: (_zetasql_ASTExceptionHandlerListProto | null);
  'astIdentifierListNode'?: (_zetasql_ASTIdentifierListProto | null);
  'astUntilClauseNode'?: (_zetasql_ASTUntilClauseProto | null);
  'astExecuteIntoClauseNode'?: (_zetasql_ASTExecuteIntoClauseProto | null);
  'astExecuteUsingArgumentNode'?: (_zetasql_ASTExecuteUsingArgumentProto | null);
  'astExecuteUsingClauseNode'?: (_zetasql_ASTExecuteUsingClauseProto | null);
  'astAuxLoadDataFromFilesOptionsListNode'?: (_zetasql_ASTAuxLoadDataFromFilesOptionsListProto | null);
  'astLabelNode'?: (_zetasql_ASTLabelProto | null);
  'astBracedConstructorFieldNode'?: (_zetasql_ASTBracedConstructorFieldProto | null);
  'node'?: "astStatementNode"|"astQueryExpressionNode"|"astSelectListNode"|"astSelectColumnNode"|"astExpressionNode"|"astAliasNode"|"astTableExpressionNode"|"astFromClauseNode"|"astWhereClauseNode"|"astGroupingItemNode"|"astGroupByNode"|"astOrderingExpressionNode"|"astOrderByNode"|"astLimitOffsetNode"|"astOnClauseNode"|"astWithClauseEntryNode"|"astWithClauseNode"|"astHavingNode"|"astTypeNode"|"astStructFieldNode"|"astSelectAsNode"|"astRollupNode"|"astStructConstructorArgNode"|"astInListNode"|"astCollateNode"|"astHavingModifierNode"|"astNullOrderNode"|"astOnOrUsingClauseListNode"|"astPartitionByNode"|"astStarExceptListNode"|"astStarModifiersNode"|"astStarReplaceItemNode"|"astUnnestExpressionNode"|"astWindowClauseNode"|"astWindowDefinitionNode"|"astWindowFrameNode"|"astWindowFrameExprNode"|"astWindowSpecificationNode"|"astWithOffsetNode"|"astAnySomeAllOpNode"|"astStatementListNode"|"astTransactionModeNode"|"astTransactionModeListNode"|"astWithConnectionClauseNode"|"astIntoAliasNode"|"astUnnestExpressionWithOptAliasAndOffsetNode"|"astPivotExpressionNode"|"astPivotValueNode"|"astPivotExpressionListNode"|"astPivotValueListNode"|"astPivotClauseNode"|"astUnpivotInItemNode"|"astUnpivotInItemListNode"|"astUnpivotClauseNode"|"astUsingClauseNode"|"astForSystemTimeNode"|"astQualifyNode"|"astClampedBetweenModifierNode"|"astFormatClauseNode"|"astPathExpressionListNode"|"astWithGroupRowsNode"|"astClusterByNode"|"astNewConstructorArgNode"|"astOptionsListNode"|"astOptionsEntryNode"|"astFunctionParameterNode"|"astFunctionParametersNode"|"astFunctionDeclarationNode"|"astSqlFunctionBodyNode"|"astTvfArgumentNode"|"astTableClauseNode"|"astModelClauseNode"|"astConnectionClauseNode"|"astCloneDataSourceListNode"|"astTransformClauseNode"|"astIndexItemListNode"|"astIndexStoringExpressionListNode"|"astIndexUnnestExpressionListNode"|"astWithPartitionColumnsClauseNode"|"astTypeParameterListNode"|"astTvfSchemaNode"|"astTvfSchemaColumnNode"|"astTableAndColumnInfoNode"|"astTableAndColumnInfoListNode"|"astTemplatedParameterTypeNode"|"astAssertRowsModifiedNode"|"astReturningClauseNode"|"astColumnAttributeNode"|"astColumnAttributeListNode"|"astStructColumnFieldNode"|"astGeneratedColumnInfoNode"|"astTableElementNode"|"astTableElementListNode"|"astColumnListNode"|"astColumnPositionNode"|"astInsertValuesRowNode"|"astInsertValuesRowListNode"|"astUpdateSetValueNode"|"astUpdateItemNode"|"astUpdateItemListNode"|"astMergeActionNode"|"astMergeWhenClauseNode"|"astMergeWhenClauseListNode"|"astPrivilegeNode"|"astPrivilegesNode"|"astGranteeListNode"|"astRepeatableClauseNode"|"astFilterFieldsArgNode"|"astReplaceFieldsArgNode"|"astSampleSizeNode"|"astWithWeightNode"|"astSampleSuffixNode"|"astSampleClauseNode"|"astAlterActionNode"|"astAlterActionListNode"|"astForeignKeyActionsNode"|"astForeignKeyReferenceNode"|"astScriptNode"|"astElseifClauseNode"|"astElseifClauseListNode"|"astWhenThenClauseNode"|"astWhenThenClauseListNode"|"astHintNode"|"astHintEntryNode"|"astUnpivotInItemLabelNode"|"astDescriptorNode"|"astColumnSchemaNode"|"astDescriptorColumnNode"|"astDescriptorColumnListNode"|"astExceptionHandlerNode"|"astExceptionHandlerListNode"|"astIdentifierListNode"|"astUntilClauseNode"|"astExecuteIntoClauseNode"|"astExecuteUsingArgumentNode"|"astExecuteUsingClauseNode"|"astAuxLoadDataFromFilesOptionsListNode"|"astLabelNode"|"astBracedConstructorFieldNode";
}

export interface AnyASTNodeProto__Output {
  'astStatementNode'?: (_zetasql_AnyASTStatementProto__Output | null);
  'astQueryExpressionNode'?: (_zetasql_AnyASTQueryExpressionProto__Output | null);
  'astSelectListNode'?: (_zetasql_ASTSelectListProto__Output | null);
  'astSelectColumnNode'?: (_zetasql_ASTSelectColumnProto__Output | null);
  'astExpressionNode'?: (_zetasql_AnyASTExpressionProto__Output | null);
  'astAliasNode'?: (_zetasql_ASTAliasProto__Output | null);
  'astTableExpressionNode'?: (_zetasql_AnyASTTableExpressionProto__Output | null);
  'astFromClauseNode'?: (_zetasql_ASTFromClauseProto__Output | null);
  'astWhereClauseNode'?: (_zetasql_ASTWhereClauseProto__Output | null);
  'astGroupingItemNode'?: (_zetasql_ASTGroupingItemProto__Output | null);
  'astGroupByNode'?: (_zetasql_ASTGroupByProto__Output | null);
  'astOrderingExpressionNode'?: (_zetasql_ASTOrderingExpressionProto__Output | null);
  'astOrderByNode'?: (_zetasql_ASTOrderByProto__Output | null);
  'astLimitOffsetNode'?: (_zetasql_ASTLimitOffsetProto__Output | null);
  'astOnClauseNode'?: (_zetasql_ASTOnClauseProto__Output | null);
  'astWithClauseEntryNode'?: (_zetasql_ASTWithClauseEntryProto__Output | null);
  'astWithClauseNode'?: (_zetasql_ASTWithClauseProto__Output | null);
  'astHavingNode'?: (_zetasql_ASTHavingProto__Output | null);
  'astTypeNode'?: (_zetasql_AnyASTTypeProto__Output | null);
  'astStructFieldNode'?: (_zetasql_ASTStructFieldProto__Output | null);
  'astSelectAsNode'?: (_zetasql_ASTSelectAsProto__Output | null);
  'astRollupNode'?: (_zetasql_ASTRollupProto__Output | null);
  'astStructConstructorArgNode'?: (_zetasql_ASTStructConstructorArgProto__Output | null);
  'astInListNode'?: (_zetasql_ASTInListProto__Output | null);
  'astCollateNode'?: (_zetasql_ASTCollateProto__Output | null);
  'astHavingModifierNode'?: (_zetasql_ASTHavingModifierProto__Output | null);
  'astNullOrderNode'?: (_zetasql_ASTNullOrderProto__Output | null);
  'astOnOrUsingClauseListNode'?: (_zetasql_ASTOnOrUsingClauseListProto__Output | null);
  'astPartitionByNode'?: (_zetasql_ASTPartitionByProto__Output | null);
  'astStarExceptListNode'?: (_zetasql_ASTStarExceptListProto__Output | null);
  'astStarModifiersNode'?: (_zetasql_ASTStarModifiersProto__Output | null);
  'astStarReplaceItemNode'?: (_zetasql_ASTStarReplaceItemProto__Output | null);
  'astUnnestExpressionNode'?: (_zetasql_ASTUnnestExpressionProto__Output | null);
  'astWindowClauseNode'?: (_zetasql_ASTWindowClauseProto__Output | null);
  'astWindowDefinitionNode'?: (_zetasql_ASTWindowDefinitionProto__Output | null);
  'astWindowFrameNode'?: (_zetasql_ASTWindowFrameProto__Output | null);
  'astWindowFrameExprNode'?: (_zetasql_ASTWindowFrameExprProto__Output | null);
  'astWindowSpecificationNode'?: (_zetasql_ASTWindowSpecificationProto__Output | null);
  'astWithOffsetNode'?: (_zetasql_ASTWithOffsetProto__Output | null);
  'astAnySomeAllOpNode'?: (_zetasql_ASTAnySomeAllOpProto__Output | null);
  'astStatementListNode'?: (_zetasql_ASTStatementListProto__Output | null);
  'astTransactionModeNode'?: (_zetasql_AnyASTTransactionModeProto__Output | null);
  'astTransactionModeListNode'?: (_zetasql_ASTTransactionModeListProto__Output | null);
  'astWithConnectionClauseNode'?: (_zetasql_ASTWithConnectionClauseProto__Output | null);
  'astIntoAliasNode'?: (_zetasql_ASTIntoAliasProto__Output | null);
  'astUnnestExpressionWithOptAliasAndOffsetNode'?: (_zetasql_ASTUnnestExpressionWithOptAliasAndOffsetProto__Output | null);
  'astPivotExpressionNode'?: (_zetasql_ASTPivotExpressionProto__Output | null);
  'astPivotValueNode'?: (_zetasql_ASTPivotValueProto__Output | null);
  'astPivotExpressionListNode'?: (_zetasql_ASTPivotExpressionListProto__Output | null);
  'astPivotValueListNode'?: (_zetasql_ASTPivotValueListProto__Output | null);
  'astPivotClauseNode'?: (_zetasql_ASTPivotClauseProto__Output | null);
  'astUnpivotInItemNode'?: (_zetasql_ASTUnpivotInItemProto__Output | null);
  'astUnpivotInItemListNode'?: (_zetasql_ASTUnpivotInItemListProto__Output | null);
  'astUnpivotClauseNode'?: (_zetasql_ASTUnpivotClauseProto__Output | null);
  'astUsingClauseNode'?: (_zetasql_ASTUsingClauseProto__Output | null);
  'astForSystemTimeNode'?: (_zetasql_ASTForSystemTimeProto__Output | null);
  'astQualifyNode'?: (_zetasql_ASTQualifyProto__Output | null);
  'astClampedBetweenModifierNode'?: (_zetasql_ASTClampedBetweenModifierProto__Output | null);
  'astFormatClauseNode'?: (_zetasql_ASTFormatClauseProto__Output | null);
  'astPathExpressionListNode'?: (_zetasql_ASTPathExpressionListProto__Output | null);
  'astWithGroupRowsNode'?: (_zetasql_ASTWithGroupRowsProto__Output | null);
  'astClusterByNode'?: (_zetasql_ASTClusterByProto__Output | null);
  'astNewConstructorArgNode'?: (_zetasql_ASTNewConstructorArgProto__Output | null);
  'astOptionsListNode'?: (_zetasql_ASTOptionsListProto__Output | null);
  'astOptionsEntryNode'?: (_zetasql_ASTOptionsEntryProto__Output | null);
  'astFunctionParameterNode'?: (_zetasql_ASTFunctionParameterProto__Output | null);
  'astFunctionParametersNode'?: (_zetasql_ASTFunctionParametersProto__Output | null);
  'astFunctionDeclarationNode'?: (_zetasql_ASTFunctionDeclarationProto__Output | null);
  'astSqlFunctionBodyNode'?: (_zetasql_ASTSqlFunctionBodyProto__Output | null);
  'astTvfArgumentNode'?: (_zetasql_ASTTVFArgumentProto__Output | null);
  'astTableClauseNode'?: (_zetasql_ASTTableClauseProto__Output | null);
  'astModelClauseNode'?: (_zetasql_ASTModelClauseProto__Output | null);
  'astConnectionClauseNode'?: (_zetasql_ASTConnectionClauseProto__Output | null);
  'astCloneDataSourceListNode'?: (_zetasql_ASTCloneDataSourceListProto__Output | null);
  'astTransformClauseNode'?: (_zetasql_ASTTransformClauseProto__Output | null);
  'astIndexItemListNode'?: (_zetasql_ASTIndexItemListProto__Output | null);
  'astIndexStoringExpressionListNode'?: (_zetasql_ASTIndexStoringExpressionListProto__Output | null);
  'astIndexUnnestExpressionListNode'?: (_zetasql_ASTIndexUnnestExpressionListProto__Output | null);
  'astWithPartitionColumnsClauseNode'?: (_zetasql_ASTWithPartitionColumnsClauseProto__Output | null);
  'astTypeParameterListNode'?: (_zetasql_ASTTypeParameterListProto__Output | null);
  'astTvfSchemaNode'?: (_zetasql_ASTTVFSchemaProto__Output | null);
  'astTvfSchemaColumnNode'?: (_zetasql_ASTTVFSchemaColumnProto__Output | null);
  'astTableAndColumnInfoNode'?: (_zetasql_ASTTableAndColumnInfoProto__Output | null);
  'astTableAndColumnInfoListNode'?: (_zetasql_ASTTableAndColumnInfoListProto__Output | null);
  'astTemplatedParameterTypeNode'?: (_zetasql_ASTTemplatedParameterTypeProto__Output | null);
  'astAssertRowsModifiedNode'?: (_zetasql_ASTAssertRowsModifiedProto__Output | null);
  'astReturningClauseNode'?: (_zetasql_ASTReturningClauseProto__Output | null);
  'astColumnAttributeNode'?: (_zetasql_AnyASTColumnAttributeProto__Output | null);
  'astColumnAttributeListNode'?: (_zetasql_ASTColumnAttributeListProto__Output | null);
  'astStructColumnFieldNode'?: (_zetasql_ASTStructColumnFieldProto__Output | null);
  'astGeneratedColumnInfoNode'?: (_zetasql_ASTGeneratedColumnInfoProto__Output | null);
  'astTableElementNode'?: (_zetasql_AnyASTTableElementProto__Output | null);
  'astTableElementListNode'?: (_zetasql_ASTTableElementListProto__Output | null);
  'astColumnListNode'?: (_zetasql_ASTColumnListProto__Output | null);
  'astColumnPositionNode'?: (_zetasql_ASTColumnPositionProto__Output | null);
  'astInsertValuesRowNode'?: (_zetasql_ASTInsertValuesRowProto__Output | null);
  'astInsertValuesRowListNode'?: (_zetasql_ASTInsertValuesRowListProto__Output | null);
  'astUpdateSetValueNode'?: (_zetasql_ASTUpdateSetValueProto__Output | null);
  'astUpdateItemNode'?: (_zetasql_ASTUpdateItemProto__Output | null);
  'astUpdateItemListNode'?: (_zetasql_ASTUpdateItemListProto__Output | null);
  'astMergeActionNode'?: (_zetasql_ASTMergeActionProto__Output | null);
  'astMergeWhenClauseNode'?: (_zetasql_ASTMergeWhenClauseProto__Output | null);
  'astMergeWhenClauseListNode'?: (_zetasql_ASTMergeWhenClauseListProto__Output | null);
  'astPrivilegeNode'?: (_zetasql_ASTPrivilegeProto__Output | null);
  'astPrivilegesNode'?: (_zetasql_ASTPrivilegesProto__Output | null);
  'astGranteeListNode'?: (_zetasql_ASTGranteeListProto__Output | null);
  'astRepeatableClauseNode'?: (_zetasql_ASTRepeatableClauseProto__Output | null);
  'astFilterFieldsArgNode'?: (_zetasql_ASTFilterFieldsArgProto__Output | null);
  'astReplaceFieldsArgNode'?: (_zetasql_ASTReplaceFieldsArgProto__Output | null);
  'astSampleSizeNode'?: (_zetasql_ASTSampleSizeProto__Output | null);
  'astWithWeightNode'?: (_zetasql_ASTWithWeightProto__Output | null);
  'astSampleSuffixNode'?: (_zetasql_ASTSampleSuffixProto__Output | null);
  'astSampleClauseNode'?: (_zetasql_ASTSampleClauseProto__Output | null);
  'astAlterActionNode'?: (_zetasql_AnyASTAlterActionProto__Output | null);
  'astAlterActionListNode'?: (_zetasql_ASTAlterActionListProto__Output | null);
  'astForeignKeyActionsNode'?: (_zetasql_ASTForeignKeyActionsProto__Output | null);
  'astForeignKeyReferenceNode'?: (_zetasql_ASTForeignKeyReferenceProto__Output | null);
  'astScriptNode'?: (_zetasql_ASTScriptProto__Output | null);
  'astElseifClauseNode'?: (_zetasql_ASTElseifClauseProto__Output | null);
  'astElseifClauseListNode'?: (_zetasql_ASTElseifClauseListProto__Output | null);
  'astWhenThenClauseNode'?: (_zetasql_ASTWhenThenClauseProto__Output | null);
  'astWhenThenClauseListNode'?: (_zetasql_ASTWhenThenClauseListProto__Output | null);
  'astHintNode'?: (_zetasql_ASTHintProto__Output | null);
  'astHintEntryNode'?: (_zetasql_ASTHintEntryProto__Output | null);
  'astUnpivotInItemLabelNode'?: (_zetasql_ASTUnpivotInItemLabelProto__Output | null);
  'astDescriptorNode'?: (_zetasql_ASTDescriptorProto__Output | null);
  'astColumnSchemaNode'?: (_zetasql_AnyASTColumnSchemaProto__Output | null);
  'astDescriptorColumnNode'?: (_zetasql_ASTDescriptorColumnProto__Output | null);
  'astDescriptorColumnListNode'?: (_zetasql_ASTDescriptorColumnListProto__Output | null);
  'astExceptionHandlerNode'?: (_zetasql_ASTExceptionHandlerProto__Output | null);
  'astExceptionHandlerListNode'?: (_zetasql_ASTExceptionHandlerListProto__Output | null);
  'astIdentifierListNode'?: (_zetasql_ASTIdentifierListProto__Output | null);
  'astUntilClauseNode'?: (_zetasql_ASTUntilClauseProto__Output | null);
  'astExecuteIntoClauseNode'?: (_zetasql_ASTExecuteIntoClauseProto__Output | null);
  'astExecuteUsingArgumentNode'?: (_zetasql_ASTExecuteUsingArgumentProto__Output | null);
  'astExecuteUsingClauseNode'?: (_zetasql_ASTExecuteUsingClauseProto__Output | null);
  'astAuxLoadDataFromFilesOptionsListNode'?: (_zetasql_ASTAuxLoadDataFromFilesOptionsListProto__Output | null);
  'astLabelNode'?: (_zetasql_ASTLabelProto__Output | null);
  'astBracedConstructorFieldNode'?: (_zetasql_ASTBracedConstructorFieldProto__Output | null);
  'node': "astStatementNode"|"astQueryExpressionNode"|"astSelectListNode"|"astSelectColumnNode"|"astExpressionNode"|"astAliasNode"|"astTableExpressionNode"|"astFromClauseNode"|"astWhereClauseNode"|"astGroupingItemNode"|"astGroupByNode"|"astOrderingExpressionNode"|"astOrderByNode"|"astLimitOffsetNode"|"astOnClauseNode"|"astWithClauseEntryNode"|"astWithClauseNode"|"astHavingNode"|"astTypeNode"|"astStructFieldNode"|"astSelectAsNode"|"astRollupNode"|"astStructConstructorArgNode"|"astInListNode"|"astCollateNode"|"astHavingModifierNode"|"astNullOrderNode"|"astOnOrUsingClauseListNode"|"astPartitionByNode"|"astStarExceptListNode"|"astStarModifiersNode"|"astStarReplaceItemNode"|"astUnnestExpressionNode"|"astWindowClauseNode"|"astWindowDefinitionNode"|"astWindowFrameNode"|"astWindowFrameExprNode"|"astWindowSpecificationNode"|"astWithOffsetNode"|"astAnySomeAllOpNode"|"astStatementListNode"|"astTransactionModeNode"|"astTransactionModeListNode"|"astWithConnectionClauseNode"|"astIntoAliasNode"|"astUnnestExpressionWithOptAliasAndOffsetNode"|"astPivotExpressionNode"|"astPivotValueNode"|"astPivotExpressionListNode"|"astPivotValueListNode"|"astPivotClauseNode"|"astUnpivotInItemNode"|"astUnpivotInItemListNode"|"astUnpivotClauseNode"|"astUsingClauseNode"|"astForSystemTimeNode"|"astQualifyNode"|"astClampedBetweenModifierNode"|"astFormatClauseNode"|"astPathExpressionListNode"|"astWithGroupRowsNode"|"astClusterByNode"|"astNewConstructorArgNode"|"astOptionsListNode"|"astOptionsEntryNode"|"astFunctionParameterNode"|"astFunctionParametersNode"|"astFunctionDeclarationNode"|"astSqlFunctionBodyNode"|"astTvfArgumentNode"|"astTableClauseNode"|"astModelClauseNode"|"astConnectionClauseNode"|"astCloneDataSourceListNode"|"astTransformClauseNode"|"astIndexItemListNode"|"astIndexStoringExpressionListNode"|"astIndexUnnestExpressionListNode"|"astWithPartitionColumnsClauseNode"|"astTypeParameterListNode"|"astTvfSchemaNode"|"astTvfSchemaColumnNode"|"astTableAndColumnInfoNode"|"astTableAndColumnInfoListNode"|"astTemplatedParameterTypeNode"|"astAssertRowsModifiedNode"|"astReturningClauseNode"|"astColumnAttributeNode"|"astColumnAttributeListNode"|"astStructColumnFieldNode"|"astGeneratedColumnInfoNode"|"astTableElementNode"|"astTableElementListNode"|"astColumnListNode"|"astColumnPositionNode"|"astInsertValuesRowNode"|"astInsertValuesRowListNode"|"astUpdateSetValueNode"|"astUpdateItemNode"|"astUpdateItemListNode"|"astMergeActionNode"|"astMergeWhenClauseNode"|"astMergeWhenClauseListNode"|"astPrivilegeNode"|"astPrivilegesNode"|"astGranteeListNode"|"astRepeatableClauseNode"|"astFilterFieldsArgNode"|"astReplaceFieldsArgNode"|"astSampleSizeNode"|"astWithWeightNode"|"astSampleSuffixNode"|"astSampleClauseNode"|"astAlterActionNode"|"astAlterActionListNode"|"astForeignKeyActionsNode"|"astForeignKeyReferenceNode"|"astScriptNode"|"astElseifClauseNode"|"astElseifClauseListNode"|"astWhenThenClauseNode"|"astWhenThenClauseListNode"|"astHintNode"|"astHintEntryNode"|"astUnpivotInItemLabelNode"|"astDescriptorNode"|"astColumnSchemaNode"|"astDescriptorColumnNode"|"astDescriptorColumnListNode"|"astExceptionHandlerNode"|"astExceptionHandlerListNode"|"astIdentifierListNode"|"astUntilClauseNode"|"astExecuteIntoClauseNode"|"astExecuteUsingArgumentNode"|"astExecuteUsingClauseNode"|"astAuxLoadDataFromFilesOptionsListNode"|"astLabelNode"|"astBracedConstructorFieldNode";
}
