name: generate-java

on:
  workflow_dispatch:

jobs:
  gen-java:
    runs-on: ubuntu-latest

    steps:
      - name: checkout zetasql
        uses: actions/checkout@v3
        with:
          repository: fivetran/zetasql

      - name: install bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.0.0

      - name: build
        run: |
          bazel build //java/com/google/zetasql/parser
          bazel build //java/com/google/zetasql/resolvedast

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gen java results
          path: bazel-bin/java/**/*
