name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zetasql
        uses: actions/checkout@v2
        with:
          repository: pgrivachev/zetasql
          path: build/zetasql-linux

      - name: Set variables
        working-directory: build/zetasql-linux
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Cache zetasql build
        id: cache-zetasql-build
        uses: actions/cache@v2
        with:
          path: build/zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so
          key: linux-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Install Bazel
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true'
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.7.2

      - name: Build
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true'
        working-directory: build/zetasql-linux
        run: bazel build ...

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout zetasql
        uses: actions/checkout@v2
        with:
          repository: pgrivachev/zetasql
          path: build/zetasql-macos

      - name: Set variables
        working-directory: build/zetasql-macos
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Cache zetasql build
        id: cache-zetasql-build
        uses: actions/cache@v2
        with:
          path: build/zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib
          key: macos-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Install Bazel
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true'
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.7.2

      - name: Build
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true'
        working-directory: build/zetasql-macos
        run: bazel build //zetasql/local_service:libremote_server.dylib --copt="-Wno-error=c99-extensions"

      - name: Set install name
        working-directory: build/zetasql-macos
        run: install_name_tool -id "@loader_path/libremote_server.dylib" bazel-bin/zetasql/local_service/libremote_server.dylib

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  package:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
      - name: Checkout zetasql-npm
        uses: actions/checkout@v2
        with:
          path: build/zetasql-npm

      - name: Load build linux
        id: cache-zetasql-linux
        uses: actions/cache@v2
        with:
          path: build/zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so
          key: linux-${{ needs.build-linux.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Load build macos
        id: cache-zetasql-macos
        uses: actions/cache@v2
        with:
          path: build/zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib
          key: macos-${{ needs.build-macos.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Copy files
        working-directory: build
        run: |
          mkdir -p zetasql-npm/lib/zetasql
          cp zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib zetasql-npm/lib/zetasql/
          cp zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so zetasql-npm/lib/zetasql/
          cp -R zetasql-npm/src/protos zetasql-npm/lib/protos

      - name: Build and Test
        working-directory: build/zetasql-npm
        run: |
          echo ${{ github.ref }}
          npm install
          npm run compile
          npm run test

      - name: Cache package results
        id: cache-package
        uses: actions/cache@v2
        with:
          path: build/zetasql-npm
          key: package-results-${{ needs.build-linux.outputs.sha_short }}-${{ needs.build-macos.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Load package results
        id: cache-package-results
        uses: actions/cache@v2
        with:
          path: build/zetasql-npm
          key: package-results-${{ needs.build-linux.outputs.sha_short }}-${{ needs.build-macos.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - uses: actions/setup-node@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: build/zetasql-npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
