name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      buildMode:
        description: 'Build mode'
        required: true
        type: choice
        options:
          - build
          - build and publish

jobs:
  build-zetasql:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
          - working-directory: build/zetasql-macos
          - cache-path: build/zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib

          - os: ubuntu-latest
          - working-directory: build/zetasql-linux
          - cache-path: build/zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so

    steps:
      - name: Checkout zetasql
        uses: actions/checkout@v2
        with:
          repository: pgrivachev/zetasql
          path: ${{ matrix.working-directory }}

      - name: Set variables
        working-directory: ./${{ matrix.working-directory }}
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Cache zetasql build results
        id: cache-zetasql-build
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cache-path }}
          key: build-results-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Install Bazel
        if: steps.cache-zetasql.outputs.cache-hit != 'true'
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.7.2

      - name: Build macos
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true' && matrix.os == 'macos-latest'
        working-directory: ./${{ matrix.working-directory }}
        run: bazel build //zetasql/local_service:libremote_server.dylib --copt="-Wno-error=c99-extensions"

      - name: Set install name (macos)
        if: matrix.os == 'macos-latest'
        run: install_name_tool -id "@loader_path/libremote_server.dylib" /build/zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib

      - name: Build linux
        if: steps.cache-zetasql-build.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-latest'
        working-directory: ./${{ matrix.working-directory }}
        run: bazel build ...

  package:
    runs-on: ubuntu-latest
    needs: build-zetasql
    steps:
      - name: Checkout zetasql-npm
        uses: actions/checkout@v2
        with:
          path: build/zetasql-npm

      - name: Load build results
        id: cache-zetasql-build-results
        uses: actions/cache@v2
        with:
          path: |
            build/zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib
            build/zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so
          key: build-results-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      - name: Copy files
        working-directory: ./build
        shell: bash
        run: |
          mkdir -p zetasql-npm/lib/zetasql
          cp zetasql-macos/bazel-bin/zetasql/local_service/libremote_server.dylib zetasql-npm/lib/zetasql/
          cp zetasql-linux/bazel-bin/zetasql/local_service/libremote_server.so zetasql-npm/lib/zetasql/
          cp -R zetasql-npm/src/protos zetasql-npm/lib/protos

      - name: Build and Test
        working-directory: ./build/zetasql-npm
        run: |
          echo ${{ github.ref }}
          npm install
          npm run compile
          npm run test

      - name: Cache package results
        id: cache-package
        uses: actions/cache@v2
        with:
          path: /build/zetasql-npm
          key: package-results-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

  publish-npm:
    if: github.event.inputs.buildMode == 'build and publish'
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Load package results
        id: cache-package-results
        uses: actions/cache@v2
        with:
          path: /build/zetasql-npm
          key: package-results-${{ steps.vars.outputs.sha_short }}-${{ secrets.CACHE_VERSION }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: ./build/zetasql-npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
