name: CI-snowflake

on:
  push:
    paths:
      - 'snowflake/**'
      - '.github/workflows/snowflake.yml'
      - '.github/workflows/base-workflow.yml'
    branches:
    tags:
      - 'sf-v*'

  workflow_dispatch:

jobs:
  npm-package:
    uses: ./.github/workflows/base-workflow.yml
    with:
      cpp-repo-name: zetasql-snowflake
      npm-package-name: snowflake
      tag: sf-v
