name: CI-snowflake

on:
  push:
    branches:
    tags:
    paths:
      - "snowflake/**"
      - ".github/workflows/snowflake.yml"

  workflow_dispatch:

jobs:
  zetasql:
    uses: ./.github/workflows/base-workflow.yml
    with:
      cpp-repo-name: zetasql-snowflake
      npm-package-name: snowflake
      tag: sf-v
