name: CI-zetasql

on:
  push:
    paths:
      - 'zetasql/**'
      - '.github/workflows/zetasql.yml'
      - '.github/workflows/base-workflow.yml'
    branches:
    tags:

  workflow_dispatch:

jobs:
  npm-package:
    uses: ./.github/workflows/base-workflow.yml
    secrets: inherit
    with:
      cpp-repo-name: zetasql
      npm-package-name: zetasql
      tag: bq-v
