name: CI-zetasql

on:
  push:
    branches:
    tags:
    paths:
      - "zetasql/**"
      - ".github/workflows/zetasql.yml"

  workflow_dispatch:

jobs:
  zetasql:
    uses: ./.github/workflows/base-workflow.yml
    with:
      cpp-repo-name: zetasql
      npm-package-name: zetasql
      tag: bq-v
